src/constructors/css.js, src/constructors/test/css.test.js, src/media/index.js, src/models/MediaQuery.js, src/models/MediaQuery.test.js
This currently only handles the most simple of cases, I'm a bit stumped where to add support for more complex media queries with logical operators. Any pointers?
Closes #5
=> Add AWESOME media query parsing support

package.json, src/constructors/element.js, src/constructors/test/element.test.js
=> Added displayname to returned component

.eslintrc, .flowconfig, .travis.yml, package.json, src/constructors/concat.js, src/constructors/element.js, src/constructors/media.js, src/constructors/nested.js, src/constructors/pseudo.js, src/constructors/rule.js, src/constructors/styled.js, src/constructors/toggle.js, src/constructors/trait.js, src/index.js, src/models/MediaQuery.js, src/models/NestedSelector.js, src/models/Root.js, src/models/Rule.js, src/models/RuleSet.js, src/models/ValidRuleSetChild.js
I setup Flow, and typed most of the files.
The one I'm really struggling with is `css.js` (surprisingly, typing the meat of the library is hard!), would appreciate help!
Would love some help with this!
/cc @ryyppy
=> Setup Flow Types

src/constructors/injectGlobal.js, src/index.js
- `global` is now `injectGlobal`
=> Rename global to injectGlobal

README.md, docs/README.md, docs/css-we-support.md, docs/tagged-template-literals.md, docs/tips-and-tricks.md
On a call now. What do you think of these changes?
=> Docs additions

src/models/ComponentStyle.js, src/test/e2e.test.js, src/utils/autoprefix.js
I'm just building on what Glamor uses, which isn't perfect but isn't bad. The only postcss one I could find was autoprefixer but it's way too heavy for our needs. Aphrodite have their own which looks ok but was a bit harder to work with than Glamor's, so I went with it.
=> Autoprefixer

package.json, src/index.js, src/models/StyledComponent.js, src/models/StyledNativeComponent.js, src/models/ThemeProvider.js, src/models/test/ThemeProvider.test.js, src/native/index.js, src/test/e2e.test.js, src/utils/create-broadcast.js
This currently adds a (completely detached) `ThemeProvider` component and removes `theme.update`. (as per @gaearon's suggestion)
Discuss!
=> Theming v2

README.md
=> Changed “Javascript” to “JavaScript”

docs/tips-and-tricks.md
See change.
Or was that intentional?
=> Changed duplicate comment

README.md
Hey, guys. Nice job you've done here.
I've just migrated a project from Radium to styled-components and added it to README.
Repo: https://github.com/diegohaz/arc
Demo: https://diegohaz.github.io/arc
=> Add ARc to README

src/models/StyledComponent.js, src/models/StyledNativeComponent.js, src/test/e2e.test.js
=> Fix default props when extending styled components

CHANGELOG.md, src/models/ThemeProvider.js
Closes #97
@dmitweb would you mind verifying that this fixes your issue? Thanks!
=> Fix ThemeProvider HMR

src/vendor/glamor/sheet.js
=> Add IE10 support

README.md, docs/api.md, docs/tagged-template-literals.md
=> Recommend usage of defaultProps in docs

README.md
Adds a section about linting to the README to help people find the stylelint processor!
=> Add section about linting to README

README.md
gitter has been super helpful to me!
=> Added gitter chat badge

README.md
=> Add react-boilerplate, postcss.parts to readme

README.md
Added to "Built with `styled-components`":
- [Hedron](http://github.com/jsbros/hedron)
- [uiGradients](http://jsbros.github.io/uigradients)
=> added Hedron and uiGradients to "Built with..."

docs/tips-and-tricks.md
As suggested by @mxstbr on #182.
=> Added Media Template section to Tips and Tricks

README.md
Thanks for this great lib, @mxstbr!
=> Added a link to react-presents under "Built with" section

docs/faq.md
=> Fix spelling mistakes in FAQ

README.md
Add react-enhanced form to build with s-c section
=> Add react-enhanced-form to build with s-c + typo

README.md
Add react-teleportation to build with s-c section
=> Add react-teleportation to build with s-c

CHANGELOG.md, package.json, src/test/css.test.js, src/utils/autoprefix.js, yarn.lock
=> Switch to using inline-style-prefixer

CHANGELOG.md
And some bad links. Also add a link to issue solved by merged PR.
=> Fix Markdown syntax

.travis.yml
=> Travis: Add node 7 and cache

appveyor.yml
=> Appveyor: Changing node versions to 6

docs/flow-support.md
=> Typo in flow-support readme

src/models/InlineStyle.js
Could somebody test this as I don’t have access to RN right now!
=> Add workarounds for more border properties

src/test/css.test.js
These tests are failing in all PRs for no reason
=> Fix unnecessary test failures

CHANGELOG.md, src/models/StyledComponent.js, src/models/StyledNativeComponent.js, src/test/basic.test.js
Avoid
```Warning: Unknown prop `innerRef` on <textarea> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop```
=> Do not pass innerRef to the component

.eslintignore, .eslintrc, .travis.yml, CHANGELOG.md, native.js, package.json, rollup.config.js, src/hoc/withTheme.js, src/models/ThemeProvider.js, src/utils/domElements.js, yarn.lock
* Fixes the flow errors that have made it to master.
* Adds `npm run flow` to CI.
* Adds lint-rules from flowtype plugin.
=> Add flow to Travis script and fix flow errors

CHANGELOG.md, src/native/index.js
Official button component was introduced in react-native@0.37.0
=> adding the <Button> of react-native entry point

README.md
Completly styled with awesome 💅  `styled-components`
=> add SpaceExperience to the "Built with" section

README.md
Added sachagreif.com to list of sites built with sc
=> Added sachagreif.com to list of sites built with sc

README.md
Add [last-draft](https://github.com/vacenz/last-draft) to examples
=> Add last-draft to examples

CHANGELOG.md, README.md, src/models/StyledComponent.js, src/models/StyledNativeComponent.js, src/test/basic.test.js
Related issue #367 , hope this is correct way to determine these.
=> Fix #367 innerRef

CHANGELOG.md, src/models/StyledNativeComponent.js
Rebased #279 because I messed up the merge commit there. (sorry @michalkvasnicak! Preserved your commit though 😊)
Fixes #245
=> Fix missing setNativeProps in StyledNativeComponent

.travis.yml, appveyor.yml
=> Fixed ci config

CHANGELOG.md, src/models/StyleSheet.js, src/models/test/StyleSheet.test.js
This is the same issue I was fixing [here](https://github.com/styled-components/styled-components/pull/391), but solved on the right branch and not in `/vendor`.
=> fix SSR issue in v2 and not in vendor

README.md
=> Reactiflux :)

package.json
=> Fix #413 #409

docs/tips-and-tricks.md
=> Update tips and tricks doc

CHANGELOG.md, package.json, src/constructors/test/injectGlobal.test.js, src/test/css.test.js, yarn.lock
This PR :
- add tests for the problem explained into #493
- upgrade stylis to v1.1.3
- do a minor fix on another test that was no longer valid after stylis upgrade
=> [v2] fix @font-face rule support

README.md
https://github.com/diegohaz/styled-theme
=> Add styled-theme to Built with section

README.md
https://github.com/diegohaz/styled-tools
Example:
```jsx
import styled from 'styled-components'
import { prop, ifProp } from 'styled-tools'
const Button = styled.button`
color: ${prop('color', 'red')};
font-size: ${ifProp({ size: 'large' }, '20px', '14px')};
background-color: ${ifProp('opaque', prop('backgroundColor', 'blue'), 'transparent')};
`
// renders with color: blue
<Button color="blue" />
// renders with color: red
<Button />
// renders with font-size: 20px
<Button size="large" />
```
=> Add styled-tools to README.md

README.md
Moved my [SASS](https://github.com/digitaledgeit/sass-spacing) margin and padding mixins to `styled-components`. Sharing is caring right?!
=> Added a package to `Built with`

package.json, src/models/test/StyleSheet.test.js, yarn.lock
Updates stylis to the new versions, which should fix some CSS parsing issues. Please test this release and let us know how it goes in #453!
=> Release 2.0 beta 4

.github/ISSUE_TEMPLATE.md, README.md
With the new (awesome!) version of webpackbin all of our old links
"broke", so this moves all of them over to the new v2 of webpackbin
:tada:
=> Fix all webpackbins

README.md
=> Add styled-ax to built-with section

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
This is due to an advise from Sean Larkin: https://twitter.com/TheLarkInn/status/847930416749092864
It adds a badge for the bundle size, gzipped bundle size, a brief contributor guide and the Contributor Covenant code of conduct.
=> [V2] Add bundle size & module badges, contributor guide, and code of conduct

README.md
Added a new styled-components boilerplate to the readme! 😄 
* [Superstylin'](https://github.com/bntzio/gatsby-starter-superstylin): a gatsby starter with styled-components 💅 
Check it out! I made this boilerplate to easily create a [gatsby](https://github.com/gatsbyjs/gatsby) site w/styled-components support. 
Have a good day! 👍
=> Add gatsby-starter-superstylin boilerplate

.npmignore, package.json
=> Replace .npmignore with explicit files list in package.json for v2

src/models/ComponentStyle.js, src/test/basic.test.js
A change in ComponentStyle messed up the order in production.
Fix #676
=> [v2] Fix CSS rule ordering regression

README.md
Add `reactour` as a library that use `styled-components` ([related](https://twitter.com/elrumordelaluz/status/847767274752790530))
=> Add reactour in #Built with styled-components section

README.md
This was a point of confusion for me when I was getting set up with styled-components in react native.
=> Add native style prop note

docs/README.md
It seems to be important enough to be in the table of contents.
I put it below theme in which security is mentioned.
=> Add security.md to the table of contents

README.md
[react-create-component-from-tag-prop](https://github.com/jameslnewell/react-create-component-from-tag-prop)
Built as a response to https://github.com/styled-components/styled-components/issues/494#issuecomment-297834933
=> Added a helper to README.md

docs/react-native.md
This pull request resolves #782
=> Added createAnimatedComponent to native documentation

README.md
=> Add two libraries to build with s-c

README.md
> Built something with styled-components? Submit a PR and add it to this list!
Thought I'd add my portfolio to the list. Will release the final version in June, with some more styled-components goodies, but it's already fully functional and might be helpful to people that want to implement SSR with styled-components v2.
Let me know if I should change anything or if this isn't the kind of website you'd like to add to the readme. Thanks!
=> Add website to readme

typings/styled-components-test.tsx, typings/styled-components.d.ts
Add Typescript definition and type tests for `ServerStyleSheet`. 
Fixes #838
=> Add typescript definition for ServerStyleSheet

README.md
I find it very useful. But then I'm biased. 😆
=> Added reference to styled-components-theme lib

CHANGELOG.md, src/models/StyledComponent.js, src/models/StyledNativeComponent.js, src/native/test/native.test.js, src/test/extending.test.js
=> Fix extend for 3 or more inheritances (Fix #780)

README.md
React-Flexa differs from other grid systems in its way it implements the CSS spec for flexbox one-to-one, enabling it to be intuitive and easy to pick up. 
It also enables you to change values responsively on breakpoints unlike many other styled-component grid systems for React.
=> Add react-flexa to grid systems within README.md

README.md
Added a personal portfolio to the README. Uses styled-components with some fun animation/transitions.
=> Update README 'built-with' section

README.md
Hi there! I made a small marketing website with this library, and wonder if this is something you'd like to add in the Readme. It changes theme colors on refresh and has an HOC for adding lines to the sides of headers, so it could give ideas to beginners.
Thanks for all the work, can't say enough words on how much I love this library <3
=> Add another website to readme

package.json, rollup.config.js, yarn.lock
=> Remove dependencies from es bundle

README.md
As suggested by [Max](https://twitter.com/mxstbr/status/886378768301924354) I thought I'd submit a PR. Hopefully this will help anyone else thinking of doing the same thing as I did.
=> Added link to video on creating a style guide using NPM

README.md
=> Changed Styled Components to styled-components

README.md
Didn't catch that while merging some PRs.
=> Fix some inconsistency in Reamde

README.md
I think it's useful for others using styled-components.
=> Add styled-media-query to libraries

dangerfile.js
Feel free to close this if you don't agree - just seems unnecessary.
=> chore: fix danger test logic, test-only changes shouldn't need a changelog entry

CHANGELOG.md, src/native/index.js
Adds `ImageBackground` to react-native aliases.
=> Add ImageBackground to native aliases

CHANGELOG.md, src/utils/generateAlphabeticName.js
Trivial change, but figured maybe this was accidentally let through :p
=> refactor use charsLength instead of chars.length

CHANGELOG.md, package.json, src/test/__snapshots__/ssr.test.js.snap, src/test/ssr.test.js, src/test/utils.js, yarn.lock
=> test: jest 20, switch ssr tests to snapshots and use node environment

README.md
Apologies, I screwed up the last pull request. I've added it at the end :)
=> Added grabient.com to Built with section in readme

README.md
As far as I know this is the first CSS grid (`display: grid`) component system built with styled-components.
https://github.com/azz/styled-css-grid/
=> Add yet another grid system to README

package.json, yarn.lock
**What**:
Upgrading bundlesize to 0.13.2
**Why**:
This update adds a better UI for details page: https://github.com/siddharthkp/bundlesize/issues/55#issuecomment-315567994
**How**:
Update version in `package.json` and `yarn.lock`
=> Upgrade bundlesize to 0.13.2

README.md
Added neat-components to the list of grid systems.
=> Added neat-components to the list of grid libraries.

README.md
=> Update styled-props demos url

.eslintrc, CHANGELOG.md, package.json, src/models/BrowserStyleSheet.js, src/models/ServerStyleSheet.js, src/test/ssr.test.js, src/test/styles.test.js, src/utils/nonce.js
I believe this should be detected and replaced by webpack as intended.
=> refactor: add a util to grab the webpack nonce magic string

README.md
Fix for https://github.com/styled-components/awesome-styled-components/issues/13
=> Adding link to awesome-styled-components

.github/ISSUE_TEMPLATE.md
- Add some updated notes
- Add concise lists instead of long texts
- Add emojis to highlight sections
- Add ALL CAPS text where appropriate
This might help to avoid more issues that are already answered (?)
=> Update issue template and add attention grabbers

CHANGELOG.md, rollup.config.js
Closes: https://github.com/styled-components/styled-components/issues/1355
=> fix: allow process.env only in es bundle

CONTRIBUTING.md, CORE_TEAM.md
- Rephrases some things
- Adds more information
- Documents release process on `npm`
- Notes CoC in Community guidelines
=> Make some more updates to the community guidelines

README.md
Example code that maintainers can add to their readme to show off styled-components!
=> Provide GitHub Badge in readme

rollup.config.js
Remove object spread from rollup.config.js and replace with Object.assign.
Per @mxstbr's suggestion https://twitter.com/mxstbr/status/951479813910429696
=> Remove object spread from rollup.config.js

native/index.js, rollup.config.js
This PR fixes the broken import of styled-components in React Native.
=> Fix name of dist bundle for React Native

sandbox/src/App.js, sandbox/src/Button.example.js
An attempt to improve the sandbox example button stylings, especially regarding their appearance on mobile devices.
=> refactor sandbox example buttons to especially improve mobile appearance

README.md
=> docs: fix the spectrum link 

CHANGELOG.md, src/no-parser/index.js
=> Add deprecation warning to preprocess bundle

package.json, yarn.lock
=> update node typings

CHANGELOG.md, src/utils/test/validAttr.test.js, src/utils/validAttr.js
Following #1752, I have added support of x-* attributes
=> support x attributes

.eslintrc, CHANGELOG.md, src/models/ComponentStyle.js, src/models/StyledComponent.js, src/models/StyledNativeComponent.js, src/native/test/native.test.js, src/test/basic.test.js, src/utils/generateDisplayName.js, src/utils/test/generateDisplayName.test.js, yarn.lock
=> hoist non react & sc statics

CHANGELOG.md, src/models/ServerStyleSheet.js, src/test/__snapshots__/ssr.test.js.snap, src/test/ssr.test.js
Closes #1757 
This is how it should have been implemented in the first place, my stream knowledge at the time was just a bit lacking!
=>  reimplement streaming as a transform stream

.flowconfig, src/models/StyledComponent.js, src/test/attrs.test.js
=>  shallow merge style object if present in both props and attrs

CHANGELOG.md, native/index.d.ts, tslint.json, typings/styled-components.d.ts
=> Fix broken isStyledComponent type

CHANGELOG.md
Add description of changes from https://github.com/styled-components/styled-components/pull/1930
=> Add keyframes changes to CHANGELOG

CHANGELOG.md, src/constructors/createGlobalStyle.js
=> prevent cGS styles from being lost in an out-of-order render / unmount cycle

src/base.js, src/constructors/keyframes.js, src/constructors/test/keyframes.test.js, src/test/rehydration.test.js, src/test/ssr.test.js, src/test/utils.js
=> remove keyframes factory

src/models/StyledComponent.js
=> Forward inner ref

src/constructors/createGlobalStyle.js, src/test/utils.js
I don't love this solution but it does work.
=> fix createGlobalStyle HMR issue

CHANGELOG.md, src/test/styles.test.js, src/utils/stringifyRules.js
this fixes the failing test case and another edge case
Fixes #2108 
Fixes the second issue noted toward the end of #2095
=> reimplement self-reference replacement as a stylis plugin

sandbox/server/webpack.config.js, sandbox/util.js
Fix https://github.com/styled-components/styled-components/issues/2136
=> Fix resolving react-dom in sandbox

src/models/StyledComponent.js, src/utils/classNameUsageCheckInjector.js, src/utils/test/classNameUsageCheckInjector.test.js
Follow https://github.com/styled-components/styled-components/issues/2159#issuecomment-433746372
=> Make classnames warnings warn once

.eslintignore, .eslintrc.json, .flowconfig, sandbox/.eslintignore, sandbox/.eslintrc, sandbox/src/App.js, sandbox/yarn.lock, src/test/basic.test.js
closes #2146 by proving it works
closes #2155 by upgrading the sandbox version of React and aliasing in `React`
make sure react-is, react, and react-dom are all updated and on the same version
=> add test for React "memo" HOC

CHANGELOG.md, src/models/StyledComponent.js, src/models/StyledNativeComponent.js, src/native/test/native.test.js, src/primitives/test/primitives.test.js, src/test/attrs.test.js
=>  ensure theme is accessible to function-form attrs 

CHANGELOG.md, src/constructors/createGlobalStyle.js, src/constructors/test/createGlobalStyle.test.js
closes #2209
Unfortunately with StrictMode and ConcurrentMode components are
intentionally rendered multiple times.
=> remove createGlobalStyle multimount warning

src/models/StyleTags.js
Hi! Thank you for your work!
I corrected some typos in the comments.
=> Fix typos in the comments

packages/styled-components/src/utils/error.js, packages/styled-components/src/utils/test/__snapshots__/error.test.js.snap, src/utils/errors.md
This fixes a broken link due to the restructure of the repository
=> Fix errors.md link

src/utils/errors.md
Reverts styled-components/styled-components#2430
=> Revert "Delete unused src folder."

packages/styled-components/src/constructors/keyframes.js, packages/styled-components/src/test/overriding.test.js, packages/styled-components/src/utils/classNameUsageCheckInjector.js
Noticed that there were a few linting errors, so here's some fixes
=> Some small linting fixes

packages/styled-components/src/utils/classNameUsageCheckInjector.js
https://github.com/styled-components/styled-components/pull/2080
=> #2080 forgot to replace \n to '' in className

CHANGELOG.md, packages/styled-components/src/base.js, packages/styled-components/src/models/StyleSheetManager.js
We're doing it for theme, so why not. Closes #2418 with what we're willing to expose.
Consider this a more minimal version of #2436
=> expose StyleSheetContext and StyleSheetConsumer

CHANGELOG.md, packages/styled-components/src/macro/index.js, packages/styled-components/src/macro/test/__snapshots__/macro.test.js.snap, packages/styled-components/src/macro/test/macro.test.js
Follow-up to #2427 for canary.
=> Fix macro with ts canary

packages/styled-components/package.json, yarn.lock
Fixes https://github.com/styled-components/styled-components/issues/2552
=> Bump version for @emotion/is-valid-props

packages/styled-components/src/models/ComponentStyle.js, packages/styled-components/src/models/test/StyleSheetManager.test.js, packages/styled-components/src/models/test/__snapshots__/StyleSheetManager.test.js.snap, packages/styled-components/src/test/__snapshots__/ssr.test.js.snap, packages/styled-components/src/test/basic.test.js, packages/styled-components/src/test/constants.test.js, packages/styled-components/src/test/props.test.js, packages/styled-components/src/test/rehydration.test.js, packages/styled-components/src/test/ssr.test.js, packages/styled-components/src/test/staticCaching.test.js, packages/styled-components/src/test/styles.test.js
closes #2631 
regardless of HMR being on or not
@kitten there's one failing test for rehydration that appears to be a legitimate failed handling case, mind taking a look?
=> disable ComponentStyle staticness in non-production modes

packages/styled-components/src/constructors/createGlobalStyle.js, packages/styled-components/src/utils/determineTheme.js
Fixes #2646 
Original sandbox: https://codesandbox.io/s/verdy
Sandbox with the fix: https://codesandbox.io/s/styled-components-whkit?fontsize=14
=> fix determineTheme impl and usage

packages/styled-components/src/models/StyledComponent.js, packages/styled-components/src/test/theme.test.js
=> add console.error to catch theme references wo prop present

packages/styled-components/src/models/StyledComponent.js, packages/styled-components/src/test/theme.test.js
=>  add lightweight dev warning when theme is consumed but not provided

packages/styled-components/src/utils/errors.md, src/utils/errors.md
=> Update error message with clickable link.

packages/styled-components/src/constructors/test/createGlobalStyle.test.js
The same fix for canary:
https://github.com/styled-components/styled-components/pull/2707
In canary, the sheet instance is saved in constructor, so this.sheet always exists when trying to delete CSS rules.
So no code change needed, just add the unit test.
=> fix: add unit test for createGlobalStyle when style tag is detached from DOM and then remove the rules

packages/styled-components/src/sheet/GroupedTag.js, packages/styled-components/src/sheet/HoistedTag.js, packages/styled-components/src/sheet/Rehydration.js, packages/styled-components/src/sheet/test/GroupedTag.test.js, packages/styled-components/src/sheet/test/HoistedTag.test.js, packages/styled-components/src/sheet/test/Rehydration.test.js, packages/styled-components/src/sheet/test/Tag.test.js, packages/styled-components/src/sheet/test/WindowedTag.test.js, packages/styled-components/src/sheet/types.js
Working on testing out the POC PR (#2771). Putting up the PR early so that @kitten or @probablyup knows it exists as I work on adding to it (and clean it up).
In the POC PR, Phil added some TODOs and comments that I'll address in this as well if he doesn't get to it before I do 😄 
Edit: I think I covered all the things in #2771 - If there's tests that could be added feel free to mention them and I can do it 😄
=> Import Rule Hoisting Testing

README.md
=> Adds object syntax to readme for documentation

packages/styled-components/package.json, packages/styled-components/src/models/StyledComponent.js, packages/styled-components/src/models/StyledNativeComponent.js, yarn.lock
Drops another 130 bytes or so, down to 12.1kB total
=> use smaller merging dep

packages/styled-components/package.json, packages/styled-components/src/models/StyledComponent.js, packages/styled-components/src/models/StyledNativeComponent.js, packages/styled-components/src/utils/mixinDeep.js, packages/styled-components/src/utils/test/mixinDeep.test.js, yarn.lock
This will ensure the ES6 syntax gets transpiled properly
Fixes #2845
=> inline mixinDeep util

packages/styled-components/src/models/StyledComponent.js, packages/styled-components/src/test/__snapshots__/expanded-api.test.js.snap, packages/styled-components/src/test/attrs.test.js, packages/styled-components/src/test/expanded-api.test.js, packages/styled-components/src/test/theme.test.js
=> fix an attrs precedence case, align v5 with v4 by removing theme usage dev warning

packages/styled-components/example/devServer.js
Problem:
- how to implement streaming ssr example missing
- quickly test if my assumptions on streaming ssr and styled components are correct
Solution:
- add streaming ssr example to devServer in examples from [documentation](https://www.styled-components.com/docs/advanced#streaming-rendering)
=> [styled-components] streaming ssr example to devServer

packages/styled-components/example/example.js
Problem:
- quick working example that I can quickly modify the check if theming works correctly
Solution:
- add ThemeProvider to devServer Example
=> [styled-components] add ThemeProvider to Example

.github/workflows/main.yml
this need a `ACCESS_TOKEN` secret created to work
=> Use 'Inclusive Organization' action to invite contributors to organization

.travis.yml, packages/styled-components/src/models/StyleSheetManager.js, packages/styled-components/src/sheet/Sheet.js
=> fix usage of nested stylesheetmanagers in SSR

packages/styled-components/package.json, packages/styled-components/src/utils/stylis.js, packages/styled-components/src/utils/stylisPluginInsertRule.js, packages/styled-components/src/utils/test/stylisPluginInsertRule.test.js, yarn.lock
fixes #2874
(and saves some bytes)
=> inline stylis-rule-sheet

packages/styled-components/src/sheet/Rehydration.js
=> adjust rehydration regex to handle deeply-nested MQs

packages/styled-components/src/macro/test/__snapshots__/macro.test.js.snap, packages/styled-components/src/test/__snapshots__/ssr.test.js.snap, yarn.lock
=> Regenerate yarn.lock to update fsevents for node>=12

packages/styled-components/src/base.js
=> Skip multi-instance warning in test environments

packages/benchmarks/src/implementations/styled-components-v5/.gitattributes, packages/benchmarks/src/implementations/styled-components-v5/Box.js, packages/benchmarks/src/implementations/styled-components-v5/Dot.js, packages/benchmarks/src/implementations/styled-components-v5/Provider.js, packages/benchmarks/src/implementations/styled-components-v5/View.js, packages/benchmarks/src/implementations/styled-components-v5/index.js, packages/benchmarks/src/implementations/styled-components-v5/styled-components-v5.esm.js, packages/styled-components/src/constructors/test/keyframes.test.js, packages/styled-components/src/utils/generateComponentId.js, packages/styled-components/src/utils/hash.js, packages/styled-components/src/utils/stylis.js
Benchmarking against v5.0.0 I'm seeing a minor improvement
=> attempt to resolve a SSR deopt in the hashing function

packages/styled-components/package.json
fixes: https://github.com/styled-components/styled-components/issues/2988
https://github.com/emotion-js/emotion/blob/master/packages/is-prop-valid/src/props.js#L66
=> Bump is-prop-valid

CHANGELOG.md, packages/styled-components/src/primitives/index.js
=> Export useTheme in primitives entrypoint

.travis.yml, README.md, scripts/jest/config.base.js
Hi, Tom from [Codecov](https://codecov.io) here.
Some of our engineers are huge fans of `styled-components`, and I thought it would be useful to add more useful code coverage metrics to this repository. Codecov is a hosted code coverage provider with awesome features. You can checkout your first reports [here](https://codecov.io/gh/thomasrockhu/styled-components).
I would love all the feedback you have, and please don't hesitate to reach out if you have any questions.
Cheers,
Tom
Codecov ❤️'s open source and will be free forever for OSS
=> Add Code coverage metrics

packages/styled-components/src/utils/hyphenateStyleName.js
=> Fix regex breaking on IE in hyphenateStyleName

packages/styled-components/src/utils/stylis.js
Updated the URL of the comment about stylis because it was old.
=> stylis doc comment url fix

CHANGELOG.md, packages/styled-components/src/models/StyledComponent.js, packages/styled-components/src/models/StyledNativeComponent.js, packages/styled-components/src/test/props.test.js, packages/styled-components/src/types.js
This is a port of #3436 to legacy-v5
=> [v5] feat: pass elementToBeCreated to shouldForwardProp

packages/styled-components/src/utils/checkDynamicCreation.ts
Closes https://github.com/styled-components/styled-components/issues/3394
Closes https://github.com/styled-components/styled-components/issues/3409
=> feat: Check dynamic creation in React 18

packages/styled-components/src/base.ts
=> Fix missing typeof window check in src/base.ts

packages/styled-components/src/constructors/createGlobalStyle.js, packages/styled-components/src/sheet/Sheet.js
=> Fix forced server-side mode not triggering global styles (v5)

README.md
Typos fixed in bugs #3793 and #3792 please validate.
=> fixed bug #3793 and #3792

.github/workflows/test.yml, CONTRIBUTING.md, lerna.json
**What has changed**
- Add Node 18 to test matrix
- Upgrade actions and simplify config with `cache` from `actions/setup-node`
=> chore: add node 18 to test matrix

packages/styled-components/src/utils/domElements.ts
Added `use` to list of supported dom elements
Resolves #3896
=> fix: add `<use>` to domElements

packages/styled-components/src/models/test/StyleSheetManager.test.tsx
Fixed a test that was a) slightly broken and b) not actually running because it was mistakenly defined outside the describe block
=> Fix to recently added test that wasn't running

packages/styled-components/package.json
Fixes the issue raised in https://github.com/styled-components/styled-components/issues/3800#issuecomment-1453355949
=> Remove "exports" entries

packages/styled-components/src/test/styles.test.tsx
Remove a test that was duplicated in styles.test.tsx.
=> Remove duplicated test

packages/styled-components/src/utils/addUnitIfNeeded.ts, packages/styled-components/src/utils/test/addUnitIfNeeded.test.ts
Replay of #3975 against the main branch
=> fix: Do not add px to CSS variables (main branch)

packages/styled-components/src/models/Keyframes.js, packages/styled-components/src/models/StyledComponent.js, packages/styled-components/src/models/test/Keyframes.test.js, packages/styled-components/src/sheet/Sheet.js, packages/styled-components/src/sheet/test/Sheet.test.js, packages/styled-components/src/utils/setToString.js
Backport of #4042 for the v5 branch!
=> [v5] Compatibility with frozen Object prototype, part 2

packages/styled-components/src/models/StyleSheetManager.tsx
Hopefully, this should resolve #4051
=> fix: StyleSheetManager missing Stylis types

packages/styled-components/src/types.ts
Fixes https://github.com/styled-components/styled-components/issues/4085 and https://github.com/styled-components/styled-components/issues/4052
Let me know what you think :)
=> Fix untyped event handler callbacks 

packages/styled-components/src/constants.ts, packages/styled-components/src/models/StyleSheetManager.tsx, packages/styled-components/src/models/StyledComponent.ts, packages/styled-components/src/models/test/Keyframes.test.ts, packages/styled-components/src/types.ts, packages/styled-components/src/utils/error.ts, packages/styled-components/src/utils/flatten.ts, packages/styled-components/src/utils/test/flatten.test.tsx
I ran prettier locally and got a diff, so I commit it.
I think this should be prettier check in CI as well, what do you think?
=> Run prettier format

packages/styled-components/src/native/index.ts, packages/styled-components/src/native/test/native.test.tsx
this implement the feature requested here
https://github.com/styled-components/styled-components/issues/3691
https://github.com/styled-components/styled-components/issues/3646
=> add toStyleSheet function

.github/workflows/test.yml, package.json, packages/styled-components/.prettierignore, packages/styled-components/package.json, packages/styled-components/src/constructors/constructWithOptions.ts, packages/styled-components/src/constructors/test/keyframes.test.tsx, packages/styled-components/src/models/StyledComponent.ts, packages/styled-components/src/models/StyledNativeComponent.ts, packages/styled-components/src/types.ts, packages/styled-components/src/utils/hoist.ts, yarn.lock
refs https://github.com/styled-components/styled-components/pull/4118#issuecomment-1672523534
I thought it would be better to run prettier on CI, so I did the following.
- update prettier v3
- run prettier
- run prettier on CI
=> Run prettier on CI

.github/ISSUE_TEMPLATE.md
A proposed alteration to the issue template to reflect the native typescript support in v6.
=> Update typescript reference on issue template

packages/styled-components/src/index.ts, packages/styled-components/src/test/types.tsx, packages/styled-components/src/types.ts
=> fix: adopt ref typing from forwardedAs

packages/styled-components/src/constructors/constructWithOptions.ts, packages/styled-components/src/native/test/native.test.tsx
since 6.0.8 release in react native typescript complains about the types
=> fix ts warning

packages/styled-components/src/sheet/GroupIDAllocator.ts, packages/styled-components/src/sheet/test/Rehydration.test.tsx, packages/styled-components/src/test/types.tsx
Closes https://github.com/styled-components/styled-components/issues/4205
=> fix(ssr): correctly place new rules after hydrated rules

package.json, packages/styled-components/package.json, packages/styled-components/src/models/StyledComponent.ts, packages/styled-components/src/test/__snapshots__/attrs.test.tsx.snap, packages/styled-components/src/test/attrs.test.tsx, yarn.lock
Fixed the specific scenario documented in #4074.
=> fix: allow passing theme prop to child if using attrs

packages/styled-components/src/test/styles.test.tsx, packages/styled-components/src/utils/stylis.ts, packages/styled-components/tsconfig.json
=> fix: further constrain self-referencing to match v5 behavior

packages/styled-components/src/types.ts
=> Export IStyledComponentBase interface

.changeset/kind-shoes-stare.md, packages/styled-components/src/types.ts
https://github.com/styled-components/styled-components/issues/5554
=>  fix: typescipt TS4023 for ExoticComponentWithDisplayName

.changeset/stale-snakes-dance.md, packages/styled-components/src/base.ts
fixes https://github.com/styled-components/styled-components/issues/5587
=> Fix no longer existing link
