styled-components/styled-components

src/models/ComponentStyle.js
src/models/StyledComponent.js
src/vendor/README.md
src/vendor/glamor/sheet.js

Inserting a null rule on ComponentStyle creation, then reusing that on each insert. It means that
```js
const X = styled.div` .. `
const Y = styled.div` ... `
const Z = styled.div` ... `
```
will be _guaranteed_ to be injected in `X`, `Y` and `Z` order, **regardless of which order they're rendered in**. This is a much more predictable behaviour, but I'm a bit worried about the performance of replacing styles at arbitrary points in the injected styles (since it could potentially invalidate a lot of the existing CSSOM).
Still, I can't think of a better way around it for now. Better to be correct and slow than fast & wrong, at least until we have hard data about performance to base an informed decision.

Preserving declaration order

---

src/constructors/global.js
src/index.js
src/models/ComponentStyle.js
src/models/GlobalStyle.js

- Rename "emoji" to "selector" – those aren't staying emojis :wink: (though we definitely need an opt-in "emoji mode"…)
- Add { global }
**NOTE: Haven't been able to actually test this in a project because linking locally isn't working for me. PLEASE TEST**

Implement { global }

---

.gitignore
.npmignore
package.json
webpack.config.js

- Use babel-preset-latest to get all the latest ESXXXX goodies automatically
- Create normal and minified UMD build for usage with bower or a script tag
- npmignore unnecessary files to be on there (supersedes #22)

Update build process

---

package.json

It will automatically fix eslint errors in pre-commit hook. It will also not allow commit code with eslint errors.

Added lint-staged with autofix eslint config

---

package.json
src/constructors/keyframes.js
src/constructors/test/keyframes.test.js
src/index.js
src/models/GlobalStyle.js

Adds first support for
```JS
import { keyframes } from 'styled-components'
const fadeIn = keyframes`
0% {
opacity: 0;
}
100% {
opacity: 1;
}
`
```
We might need to use a different name generator (UUIDs aren't very _nice_) and we might need to optionally let people pass in a name that we prepend before our unique stuff for easier debugging.
**NOTE: UNTESTED IN REAL PROJECT, PLEASE VERIFY** (still can't `npm link`)

Add keyframes support

---

webpack.config.babel.js

This fixes the UMD build, which means you can drop a script tag in a HTML and it'll just work 💃 (as long as React is also there) `styled.keyframes`, `styled.css`, etc. also all exist, to do `styled.div` you'll have to do `styled.default.div` since it's transpiled ES6 which is good anyway.
Closes #49 
Example:
```HTML
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Test</title>
</head>
<body>
<div id="root"></div>
<script src="https://fb.me/react-15.0.0.js"></script>
<script src="https://fb.me/react-dom-15.0.0.js"></script>
<script type="text/javascript" src="./dist/styled-components.js"></script>
<script>
var _templateObject = _taggedTemplateLiteral(['\n  background-color: red;\n  width: 20px;\n  height: 20px;\n'], ['\n  background-color: red;\n  width: 20px;\n  height: …
```

Fix UMD build

---

docs/README.md

Fix the `theming.md` link
Also, the `shared-component-libraries.md` file does not exist. Do you still want to keep the link ?

docs(readme): Fix links on the table of content

---

docs/README.md

Remove the dead link from the documentation table of content, pointing to a non-existing `shared-component-libraries.md` file.

docs(readme): Remove a dead link

---

package.json
src/models/StyledComponent.js
src/models/ThemeProvider.js
src/models/test/ThemeProvider.test.js

react-router uses react-broadcast to handle context updates. We do too,
except I inlined the implementation to avoid multiple wrapper
components. That would totally be fine, except I also slightly adapted
the implementation – and that broke anything else using react-broadcast,
including react-router v4.
This PR fixes that by instead attaching our theme to this.context
directly, not to this.context.broadcasts. This avoids overlap and fixes
the bug. (manually verified)
Closes #75

Fix react-router v4

---

README.md
docs/README.md
docs/css-we-support.md
docs/existing-css.md

- Add section about the Sublime Text PR to the README
- Add "Using styled-components with existing CSS" doc (closes #85)
- Updated css-we-support to be more explicit about the fact that you can use all of CSS
- Move made-and-supported-by section to the top of the README
/cc @geelen and @samit4me for review ([live preview](https://github.com/styled-components/styled-components/blob/more-docs/README.md))

More documentation

---

src/test/e2e.test.js
src/utils/autoprefix.js

Camelizing and hyphenating breaks custom props, so if we see one of them just skip our janky autoprefixer.

Custom Properties (CSS Variables) support

---

.travis.yml
Dangerfile

Hi @mxstbr, I've integrated Danger in the project: 
- Add Dangerfile with basics rules (see #95)
- Add danger command to Travis flow
I've already created a [bot](https://github.com/StylishDangerCI) and you can use this one if you want, I give you the credentials and then you can add the token in Travis ([how to](https://danger.systems/guides/getting_started.html#creating-a-bot-account-for-danger-to-use)).
Anything else you can come up with that might be an issue with PRs more often than not!
for this one
>  Enforce that a test must be added for the changes? (not sure if this makes sense for everything, maybe enforce for all .js files in the src/ folder except for src/vendor)
Danger print a warning like this:
"There're library changes, but not tests. That's OK as long as you're refactoring …

[WIP] Setup Danger to check PRs

---

CHANGELOG.md
example/devServer.js
example/with-perf.html
src/models/StyledComponent.js

My performance testing experience is quite limited and this is the first time I've used `react-addons-perf`.
While we were perusing the styled-components code we got to wondering about the use of `generateAndInjectStyles` in the `render` method of `StyledComponent`. Our first thought was that a side-effecty method-call probably shouldn't happen in the `render` method but rather in one of the lifecycle hooks such as `componentWillReceiveProps`, therefor keeping `render` a pure method.
I wanted to add some benchmarks to see if the change made any difference as well as trying out a few other things that might have improved performance (playing around with `shouldComponentUpdate` etc).
After putting together a benchmark based on the existing example it looks like there may be a performance …

Possible performance improvement moving componentStyle.generateAndInjectStyles out of render

---

README.md

Recently adopted this incredible packag into the react-aria-tooltip component. @mxstbr reached out and asked if I would like to add it to the "Built with" list. 👍  but of course.

Adds react-aria-tooltip to "Built with" list

---

docs/tips-and-tricks.md

The doc says to use `innerRef` on a styled component to get its DOM node, but the code example uses `ref`. This change updates the code example to be consistent with the docs.

Use `innerRef` to get DOM node in the example code

---

README.md
docs/README.md
docs/faq.md

Some people had problems with styled-components in connection with webpack 2 and babel.
This adds an instruction how to solve the problem to the readme.md

Add "Using styled-components with webpack 2" to the readme.md

---

docs/tips-and-tricks.md

As per https://github.com/styled-components/styled-components/issues/182#issuecomment-260122678, this changes the Media Templates example to use `em` as the breakpoint unit to work properly cross-browser whilst supporting users who change their browser's `font-size`.
I'm a bit torn by this change, though, as it does add some complexity to the example. I glanced at the other examples that used an example of a breakpoint of `420px`, and I didn't want to go touching them, at least not yet. It is arguably a lot more difficult to think of what `26.25em` means in real world, compared to `420px`.
Source for choosing `em` over `px`: https://zellwk.com/blog/media-query-units/

Use em in Media Templates example

---

CHANGELOG.md
src/models/StyledNativeComponent.js

In react native, interpolations had access to the theme object only. This pull request fixes that. #138

pass props to interpolations in StyledNativeComponents

---

.babelrc
CHANGELOG.md
package.json
rollup.config.js
src/models/StyledComponent.js
src/models/StyledNativeComponent.js
src/models/ThemeProvider.js
src/models/test/ThemeProvider.test.js
yarn.lock

- switch Object.assign to spread operator
- rationale: babel transforms this to Object assign / or a polyfill equivalent
this way we won't need to add another module like object-assign
- please take note I don't have experience with flow annotations,
so if this is valid `return Object.assign({}, this.outerTheme, (theme: Object))`
then this PR works.

fixes #196 Converts Object.assign to spread operator

---

CHANGELOG.md
src/utils/autoprefix.js

- fixes #212
- uses regex instead of es2015 startsWith for IE10 compat

switch startsWith to normal regex

---

.travis.yml

1. You don't need sudo
2. Builds will start faster with [travis's container based infra](https://docs.travis-ci.com/user/trusty-ci-environment/#Container-based-with-sudo%3A-false)

Travis: Removed sudo for faster builds

---

README.md

Since we've merged the `css-to-react-native` implementation (thanks @jacobp100!), I've added a docs about complex styles in ReactNative to the README! 
(note, this isn't released yet, so don't merge this yet)

Add section about complex styles in ReactNative

---

CHANGELOG.md
package.json
yarn.lock

Bumps `css-to-react-native` to `1.0.3` to fix #231 for everybody installing `styled-components` afresh! /cc @jacobp100

Bump css-to-react-native to 1.0.3

---

CHANGELOG.md
src/models/AbstractStyledComponent.js
src/models/StyledNativeComponent.js

This brings the performance improvement in #137 for `StyledComponent` into `StyledNativeComponent` as well.
This also fixes #138 as props are now passed into the rules.

Only generate styles on mount or props change for StyledNativeComponent

---

.travis.yml

This should move you to 4.0.1 - which doesn't get mangled comments from the new github markdown renderer

Fix comments from Danger

---

docs/flow-support.md

Remove the duplicate `react-native.js` flow-typed file reference in the flow-support's example section.

Remove duplicate lib in flow-support's examples

---

CHANGELOG.md
src/models/StyledComponent.js
src/models/StyledNativeComponent.js
src/models/ThemeProvider.js
src/test/theme.test.js

Fix defaultProps/props theme theming

---

CHANGELOG.md
src/models/StyledComponent.js
src/models/StyledNativeComponent.js
src/test/theme.test.js

If the subscribe function triggers a state change the componentWillReceiveProps lifecycle will still have the old state. Setting a property called theme circumvents this. In my opinion this is a React bug because the subscribe function changes the state before the componentWillReceiveProps lifecycle will fire.

Fix theming

---

docs/tagged-template-literals.md

Fixed styled-components typo in the Tagged Template Literals docs page.

Fixed import typo in docs

---

CHANGELOG.md
src/models/StyledComponent.js
src/models/StyledNativeComponent.js
src/test/theme.test.js

At the initial render styled-components was taking the theme from ThemeProvider even the component had an own theme prop.

Fix overriding theme with props

---

.gitignore
.travis.yml
CHANGELOG.md
package.json
rollup.config.js
src/models/ThemeProvider.js
src/utils/flatten.js
yarn.lock

By using the `is-plain-object` (one dep, `is-object`) and the `is-function` (no deps) packages instead of using lodash utils (even when requiring them directly) we knock our min+gzip bundle size down by ~0.5kB.
(I think this is mostly due to lodash pulling in some additional files which we don't need)
Also adds the `rollup-plugin-visualizer` to the rollup build workflow, which creates a `bundle-stats.html` file that looks like this when viewed in the browser:
Very useful for keeping track of our bundle size 👍  (the above graph is for the new `stylis` bundle, in case you're wondering why it's so small. Ref #286)

Replace lodash with util packages (-0.5kB package size)

---

.babelrc
CHANGELOG.md
docs/api.md
docs/theming.md
package.json
rollup.config.js
src/hoc/withTheme.js
src/index.js
src/native/index.js
src/test/theme.test.js
yarn.lock

Fix #272.
Add the possibility to get the current theme using `withTheme(component)` syntax. The theme will be passed as a `theme` prop to the child component.

withTheme Higher Order Component (fix #272)

---

CHANGELOG.md
README.md

Related to #342 
[Link to updated rendered readme](https://github.com/styled-components/styled-components/blob/update-demo-links/README.md)

Update demo links in readme to examples with v1.2.1

---

src/models/ThemeProvider.js

Just renamed outherTheme to outerTheme.
Don't think this needs a CHANGELOG entry. 😜

Fix flow type name

---

CHANGELOG.md
src/models/StyledComponent.js

This makes sure `StyledComponent` inherits `ParentComponent`'s `contextTypes`. See this information on BabelJS's docs: https://babeljs.io/docs/usage/caveats/#internet-explorer-classes-10-and-below-

Fix themes in IE <= 10

---

CHANGELOG.md
src/models/StyledComponent.js

Fix StyledComponent.displayName is displayed as Styled(undefined) when using Stateless Component. (Using Component.name when Component.displayName is undefined)

Fix <Styled(undefined)> in React Developer Tools

---

example/ssr.js
package.json

This adds a super simple ssr example. Not sure if this is something you want, but I was testing out so I figured i might as well send it as a PR since there is no docs/examples for this yet AFAICT.
_This needs to be run with `babel-node example/ssr`_

adds simple ssr example

---

README.md

A link to module `react-styled-flexboxgrid`: Grid system based on styled-components and flexbox for React

README: add link to `react-styled-flexboxgrid`

---

CHANGELOG.md
src/constructors/test/injectGlobal.test.js
src/constructors/test/keyframes.test.js
src/models/GlobalStyle.js
src/models/GlobalStyleSheet.js
src/models/StyleSheet.js
src/test/utils.js

Putting dynamic styled component css rules into the same stylesheet
as global styles can cause global rules such as `@font-face` to be
recomputed.  Instead, create two stylesheets, one for global
styles, and one for styled-components.
Fixes part of #400.

Put global styles in a separate stylesheet.

---

README.md

Seems there is just a simple typo in the example which causes nothing to be returned from render. This adds a return.

Add return to React Native example in README

---

typings/styled-components-test.tsx
typings/styled-components.d.ts

This PR slightly improves TypeScript support (typings) of interpolations.
There're two very different contexts where styles are being created: global (`injectGlobal`, `keyframes` functions) and component (`styled` function). In the global contexts, functions as interpolations are not accepted. Indeed, there's nothing to use - no props available.
So the typings of these functions already make this distinctions, `injectGlobal` and `keyframes` do not accept functions as interpolations.
The issue comes up when `css` needs to be used. Since it is meant to be composable and can be used inside both contexts, we need to know what types of interpolations are hidden inside.
- an overload of `css` has been introduced which only takes simple interpolations
- introduced 'flatten' interpolation type to …

TypeScript: Improve typings of interpolations

---

package.json
yarn.lock

I may be wrong on the bundling thing :)
Fixes #433 
Update: I removed a commit that made all dependencies externals for rollup, that was wrong. 
Instead, I need to convince Webpack to not use the ES build, since it includes bundled deps that should not be bundled when building an app. Perhaps the ES build should not be there at all, browser can use the normal build and for ES you just point to an ES6 transpilation?

v2: Upgrade stylis, don't bundle external dependencies

---

package.json
typings/styled-components.d.ts
typings/themed-tests/mytheme-styled-components-test.tsx
typings/themed-tests/mytheme-styled-components.tsx

Ok, this follows #428 but is a bit more complex.
The issue with themes in TypeScript is that they are not strongly typed. When a component is defined on the application level, it just assumes that theme exists with a specific structure:
```ts
const Button = styled.button`
color: ${p => p.theme.primaryColor};
`;
```
Currently, the `theme` property just has type `any` which just allows any structure.
On other hand, allowing passing a theme type at the call-site is not really desirable:
```ts
//const Button = styled.button<MyTheme>` // currently is not a proper TS syntax
const Button = styled<{}, MyTheme>("button")`
color: ${p => p.theme.primaryColor};
`;
```
Note, first `{}` is an augmented props type parameter, second is an actual theme type.
I think that is really cucumbersome.
My …

TypeScript: Add support of typed themes

---

.flowconfig
CHANGELOG.md
src/constructors/test/injectGlobal.test.js
src/constructors/test/keyframes.test.js
src/models/ComponentStyle.js
src/models/GlobalStyle.js
src/models/GlobalStyleSheet.js
src/models/StyleSheet.js
src/models/test/StyleSheet.test.js
src/test/utils.js
src/types.js

Adding a separate global stylesheet broke server side rendering,
because stylesheet.rules only returned component styles.  We now
have a single stylesheet class, that inserts into the specified
sheet, and proxies all other methods to both sheets.

Add Stylesheet class that proxies methods to two stylesheets

---

CHANGELOG.md
src/models/StyledComponent.js
src/models/StyledNativeComponent.js
src/test/theme.test.js

Fix defaultProps used instead ThemeProvider after initial render

---

typings/styled-components-test.tsx
typings/styled-components.d.ts
typings/themed-tests/mytheme-styled-components-test.tsx

This small fix allows to not declare the theme prop to custom components when reexporting the styled function with a custom theme interface.
```ts
import * as React from "react";
import styled, { ThemeInterface } from "my-themed-components";
interface BoxProps {
borderBottom?: boolean;
className?: string;
}
const Box:React.StatelessComponent<BoxProps> = (props) =>
<div className={props.className}>{props.children}</div>;
const StyledBox = styled(Box)`
padding: ${props => props.theme.lateralPadding}; // <-- this gets the correct interface now
${props => props.borderBottom && `
border-bottom: 1px solid #ccc;
`}
`;
export default StyledBox;
```
/cc @Igorbek 
PS. I'll add some docs for the re-exporting styled components thing after lunch :)

[Typescript] Fix ThemedStyledInterface

---

.npmignore

Noticed that test files were being published to npm, which seems unnecessary to me.

Exclude test files from npm publish

---

README.md

Hello! 👋 
I've been experimenting with `styled-components` in a few projects. None of the grids I looked into supported setting different prop values at specific breakpoints (other than width). So I've started porting my old `SASS` packages to `styled-componnents`. I've shared them on npm to make it easier for me to use across multiple projects, and in-case anyone else might find them useful.
I'd love to add them to the `Built With` list. I'd also love some feedback on the components themselves if anyone has any spare time.
https://github.com/jameslnewell/styled-components-breakpoint
https://github.com/jameslnewell/styled-components-grid

Added two packages to the Built With section of the README

---

CHANGELOG.md
src/models/StyledComponent.js
src/test/basic.test.js

The target.name option was already on master. I was looking on Glens PR because I thought he missed something in the classname PR and it was still unfixed there. This PR only adds tests for the displayname and changes the default displayname. Sorry for the inconvenience. 😥

Change default displayName to `Styled(Component)`

---

docs/api.md

The previous example does not need to use `css` since it can simple be `toString()`ed. This example is copied from tagged-template-literals and it includes a function which clarify the need of `css`.

Use better example for `css`

---

docs/tagged-template-literals.md

There was a mistake in docs regarding ES6 tagged template literals.
Let me know if I missed something.

[Doc] Fix doc regarding ES6 tagged template literals

---

native/index.d.ts
typings/styled-components-hoc-test.tsx
typings/styled-components-test.tsx
typings/styled-components.d.ts
typings/themed-tests/mytheme-styled-components.tsx
typings/themed-tests/with-theme-test.tsx

Add withTheme definition

---

docs/faq.md

AFAIK these PR's are merged. I am running with Webpack 2 + styled components with no problem using the ES2015 preset.

Remove unnecessary advice

---

.babelrc
package.json
rollup.config.js

With the deprecation of babel-preset-latest and the addition of babel-preset-env per [babel-preset-env](https://github.com/babel/babel-preset-env) the babel.rc file as well as the rollup.config.js have been updated to use the env preset.

replaced babel-preset-latest with babel-preset-env

---

src/models/StyledComponent.js
src/models/StyledNativeComponent.js

The constructors weren't passing through their arguments to React.Component, which causes Rapscallion to fail.
Backport of https://github.com/styled-components/styled-components/pull/601

Fix component constructors not passing through arguments to React.Component (V1)

---

src/models/StyledComponent.js
src/models/StyledNativeComponent.js

Fix #600
The constructors weren't passing through their arguments to React.Component, which causes Rapscallion to fail.

Fix component constructors not passing through arguments to React.Component (V2)

---

CHANGELOG.md
no-parser.js
src/constructors/constructWithOptions.js
src/constructors/injectGlobal.js
src/constructors/keyframes.js
src/constructors/styled.js
src/constructors/test/injectGlobal.test.js
src/constructors/test/keyframes.test.js
src/index.js
src/models/ComponentStyle.js
src/models/GlobalStyle.js
src/models/StyledComponent.js
src/models/test/StyleSheet.test.js
src/native/index.js
src/no-parser/css.js
src/no-parser/flatten.js
src/no-parser/index.js
src/no-parser/stringifyRules.js
src/no-parser/test/basic.test.js
src/no-parser/test/flatten.test.js
src/test/utils.js
src/types.js
src/utils/stringifyRules.js
src/utils/test/flatten.test.js

This adds the entrypoint that accepts the preprocessed CSS from the babel plugin, which has an open PR for the preprocessing here: https://github.com/styled-components/babel-plugin-styled-components/pull/26
It needs to add new singleton factories and new arguments to some other factories, since it now passes in `css`, `flatten`, `stringifyRules` (new), and `GlobalStyle` into some things that need them.
Edit: After fixing everything up, there are still 4 failing unit tests left, which are however failing on v2 as well.

Accept preprocessed CSS from babel plugin

---

CHANGELOG.md
src/models/StyledComponent.js
src/models/StyledNativeComponent.js
src/test/theme.test.js

According to @k15a (see #574)
> Ok this is a bug with v2 only. I think I have already fixed that bug in v1 so I will have to search for the PR.
> The corresponding PR is #450.
- fix issues: #445, #574, #549
- This change to the _CHANGELOG_ is not included in this [commit](https://github.com/styled-components/styled-components/pull/450/commits/7c4f01d44e5d40921de5052d893c7f755ed90b5b#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR13) (irrelevant)

Restore PR #450. Fix #445, #574, #549

---

package.json

There are lots of interesting packages related to styled-components on NPM. Many of them are using the "styled-components" keyword so you can find them more easily.
Let's add that keyword to styled-components' package.json so it is easy to navigate from https://www.npmjs.com/package/styled-components to https://www.npmjs.com/browse/keyword/styled-components using the "keywords" links in the sidebar.

Add "styled-components" to package.json keywords

---

CHANGELOG.md
src/models/ComponentStyle.js
src/models/StyledComponent.js
src/utils/createWarnTooManyClasses.js
src/utils/generateAlphabeticName.js

#583
- Add second `BaseStyledComponent` class to not repeat methods
- Improve `propsForElement` and `this.attrs` creation
- Stop creating `this.attrs` if `attrs` doesn't exist
- Rewrite `generateAlphabeticName` to be iterative instead of recursive
```
simple component (construction)     0.019±0.003ms
simple component (first render)     0.132±0.027ms
simple component (repeated render)  0.014±0.001ms
prop changes                        0.309±0.054ms
prop shorthands (first render)      0.175±0.071ms
prop shorthands with prop changes   0.377±0.093ms
```
```
simple component (construction)     0.013±0.002ms
simple component (first render)     0.121±0.026ms
simple component (repeated render)  0.015±0.004ms
prop changes                        0.311±0.101ms
prop shorthands (first render) …
```

Improve StyledComponent performance

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

Same as #634, cherry-picked on top of master
This is due to an advise from Sean Larkin: https://twitter.com/TheLarkInn/status/847930416749092864
It adds a badge for the bundle size, gzipped bundle size, a brief contributor guide and the Contributor Covenant code of conduct.

Add bundle size & module badges, contributor guide, and code of conduct

---

CHANGELOG.md
src/models/StyledComponent.js
src/test/basic.test.js
src/utils/isStyledComponent.js

As a continuation of #639 
Fix #629 
- Pass the `innerRef` to the nested target if said target is a Styled Component.
- Replace the old `innerRef` tests that weren't actually doing much

Add nested `innerRef` for Styled Components

---

CHANGELOG.md
package.json
src/hoc/withTheme.js
src/models/AbstractStyledComponent.js
src/models/ThemeProvider.js
src/models/test/ThemeProvider.test.js
src/test/extending.test.js
yarn.lock

migrate from the deprecated React.propTypes to prop-types package

---

CHANGELOG.md
src/vendor/glamor/sheet.js

While trying to implement tests for my styled-components I was constantly facing the following error
> TypeError: Cannot read property 'cssRules' of undefined
I then managed to track its root as being the issue https://github.com/tmpvar/jsdom/issues/992.
Other browsers are also affected by this, not only jsdom, as can be seen at https://github.com/threepointone/glamor/issues/58.
Glamor has already fixed this with the commit https://github.com/threepointone/glamor/commit/98d4f44ba4335abd0e63bf946edff04ec51d3a41, and this PR brings the main change to styled-component.
----
This PR should fix https://github.com/styled-components/jest-styled-components/issues/2 and it could also be related to https://github.com/styled-components/styled-components/issues/124#issuecomment-273914589

add support to jsdom

---

CHANGELOG.md
package.json
src/hoc/withTheme.js
src/test/theme.test.js
yarn.lock

Fix #596 
See for reference:
- https://github.com/reactjs/react-redux/issues/53
- https://github.com/reactjs/react-redux/issues/276

Hoist non-static properties on withTheme HOC

---

CHANGELOG.md
src/constructors/keyframes.js
src/constructors/test/keyframes.test.js

When using `styled-components` in one of our projects we noticed that on older iOS devices (8.x, iPhone 6 and 6 Plus) animations didn't work.
After some investigation we've found http://stackoverflow.com/questions/9211261/css3-animation-not-working-in-safari and after some experimentation, the solution suggested in http://stackoverflow.com/a/34013139 worked.
This PR adds changes `keyframes` to generate both `@keyframes {name}` and `@-webkit-keyframes {name}`.

keyframes better support older iOS (8.x) webkit

---

package.json
yarn.lock

`babel-plugin-flow-react-proptypes` updated to include https://github.com/brigand/babel-plugin-flow-react-proptypes/pull/81.
Solves #741.

Resolve remaining prop-types warnings

---

package.json
yarn.lock

`babel-plugin-flow-react-proptypes` updated to include brigand/babel-plugin-flow-react-proptypes#81.

[V2] Resolve remaining prop-types warnings

---

src/models/ServerStyleSheet.js
src/models/StyleSheet.js

Proof of concept, would appreciate comments.
Makes it possible to render `{sheet.getStyleElement()}` directly in <head> using React. Current ssr solution requires that the extracted styles are injected into the html outside of React, for instance via Express string substitution. This isn't suitable in for example GatsbyJS.
This needs tests, and proper Flow thingies.
With this change, I can do something like this in Gatsby:
```jsx
class Html extends React.Component {
render() {
const helmet = Helmet.renderStatic();
// 💅
const sheet = new ServerStyleSheet();
sheet.collectStyles(this.props.body);
return (
<html lang="sv">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
{helmet.title.toComponent()}
{helmet.meta.toComponent()} …
```

Get ssr styles as React Element

---

.flowconfig

It's already included by default
https://flow.org/en/docs/config/libs/

Remove unnecessary listing `flow-typed` in [libs]

---

CHANGELOG.md
src/models/StyledComponent.js

Fix StyledComponent for older browsers IE<=10 by setting context directly on every StyledComponent class.
This isn't nice but should fix IE issues for now (?)
Shall we remove AbstractStyledComponent in the future, since it doesn't serve a purpose anymore, @geelen?

Set StyledComponent context directly on every class

---

CHANGELOG.md
src/models/StyledNativeComponent.js
src/native/test/native.test.js

In ```StyledNativeComponent```, ```setNativeProps``` has been deleted between v1 and v2.
This PR restores it to allow forwarding of native props to the inner component.
Fix #763.

[v2] Restore setNativeProps

---

CHANGELOG.md
src/models/StyledComponent.js
src/test/attrs.test.js

Previously we were handling children specifically, but if we don't, we get this interesting behaviour with attrs.
I definitely wouldn't document or recommend using `attrs({ children: '...' })` in this way but it seems odd that children doesn't work like the others, and who knows, maybe someone will come up with an interesting pattern using it?
I wouldn't have suggested doing this if it didn't simplify the implementation, so even though I'm unsure about it, I think we should merge this.

Don't treat props.children special

---

package.json
rollup.config.js

Before, even when stylis had a new patch version, Webpack 2 and Rollup would use the ES Bundle, which includes stylis. This PR changes the ES Bundle to import stylis instead.

Allow updates to stylis from being used in ES bundle

---

CHANGELOG.md
src/models/StyledNativeComponent.js
src/native/test/native.test.js

Due to the setNativeProps feature, a ref or innerRef will always be passed.
This causes a warning for stateless, functional components, since those
are not allowed to accept refs.
This changes the behaviour to pass innerRef instead and output a
warning if setNativeProps is used nonetheless.
Fix #766

Prevent ref prop from being passed to SFC

---

yarn.lock

Updated lock file to allow yarn users to get the latest 2.x stylis version with styled components.

updating version of stylis in yarn.lock file

---

CHANGELOG.md
src/test/extending.test.js

~:rotating_light: This pull request contains a failing test and should not be merged.~ *Edit: Test is no longer failing!*
Should it be possible to add `attrs` after overriding `withComponent`? I found a test for `withComponent` followed by `extend`, but none for `attrs`, so I added one:
```js
const Parent = styled.button`
color: red;
`
const Child = Parent.withComponent('a').attrs({
href: '/test'
})``
```
Currently this throws `TypeError: Parent.withComponent(...).attrs is not a function`.
I haven't looked into the implementation to see what might be causing this, but if it's an actual bug, I'd be willing to spend some time on a fix given a couple hints about where to start looking!

Test: withComponent(...).attrs is not a function

---

package.json

These should not be used anymore as we have written in the docs lately
libdef is now the easiest way to use flow with styled-components. Using
the sources as we did earlier generates a lot of errors that is hard to
avoid.
cc @styled-components/typers

Remove the flow copy logic from build process

---

CHANGELOG.md
package.json
src/models/StyleSheetManager.js
src/test/theme.test.js
src/utils/create-broadcast.js
yarn.lock

Thank you for taking the trouble to ship type definitions with your library! There are changes in Flow v0.47.0 that cause Flow to report errors that were not reported in previous versions. I put together this PR so that your users will not see errors when they upgrade to the latest Flow. And I made sure that type-checking still passes with Flow v0.43.1 (the version that you have been using).
As of v0.47.0 Flow strictly checks function arity. That means you will get an error if you call a function with more arguments than are listed in the function signature.  For details see https://flow.org/blog/2017/05/07/Strict-Function-Call-Arity/
There are also some changes to checking React component prop types. The latest Flow will report some errors that previous versions missed.
The full …

Fixes for Flow v0.47.0

---

CHANGELOG.md
package.json
src/test/css.test.js
yarn.lock

Fix ReferenceError: escade is not defined
See https://github.com/thysultan/stylis.js/issues/30

Upgrade stylis from 3.0.4 to 3.0.17 to fix a crash

---

CHANGELOG.md

Apparently some merging went wrong and removed [this change](https://github.com/styled-components/styled-components/pull/874/files) in my [pr](https://github.com/styled-components/styled-components/commit/6854486c6c791bed3cc62a7e98235f1f167a267b)

Fix CHANGELOG from last 2 merges

---

CHANGELOG.md
typings/styled-components.d.ts
typings/tests/nested-test.tsx

A following up PR to #837
- adds support of using other components in interpolations
- tests
- removes a few unnecessary `any`s
- update `CHANGELOG`

Add TypeScript support of using other styled components in selectors

---

typings/styled-components.d.ts

Fixed:
`error TS2339: Property 'svg' does not exist on type 'ThemedBaseStyledInterface<Theme>`
`error TS2339: Property 'path' does not exist on type 'ThemedBaseStyledInterface<Theme>`
and so on...

[breaking][typescript] SVG type fix

---

README.md

`react-styled-flexboxgrid` is a Grid Systems library, not a Boilerplate ;)

README: move `react-styled-flexboxgrid` to `Grid Systems`

---

README.md

I've ported language-babel from Atom to VSCode which supports styled-components syntax highlighting out of the box. I've updated the README to include this.
https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel

update vscode syntax highlighting documentation

---

package.json

Fix #921 
Note: The actual issue with this is a yarn bug, but we can circumvent it completely by including react v16 into our peer dependencies, which is a safe modification and actually the default on React Native.

Fix peer dependency of react to include v16

---

README.md

Refer to the editor of CodeSandbox instead of the homepage, since the homepage doesn't use `styled-components`. I could also link to the [styled-components sandbox](https://codesandbox.io/s/rkmNRByE4) 😄 .

Refer to the editor of CodeSandbox

---

package.json
yarn.lock

Basically this:
This will help in **keeping** the library tiny.
1. Setting the file and threshold:
The config sits inside `package.json`, the threshold is set to 9.5kB right now.
You can add multiple files here. ([docs](https://github.com/siddharthkp/bundlesize/blob/master/README.md#configuration))
2. Authorize bundlesize:
`bundlesize` needs access to github API with scope `repo:status`, You can follow the [steps here](https://github.com/siddharthkp/bundlesize/blob/master/README.md#build-status)
Here's a demo pull request in glamor's fork: https://github.com/siddharthkp/glamor/pull/1

Add library size check in CI

---

CHANGELOG.md
package.json
src/utils/stringifyRules.js
yarn.lock

This prevents bugs with shared options when different libraries all use
stylis.
~cc @thysultan Is the `keyframe ` option for namespacing broken? I'm seeing some regressions with mangled animation names.~
Edit:
```diff
-@-webkit-keyframes keyframe_880{ from{ opacity: 0; } } @keyframes keyframe_880{ from{ opacity: 0; } } .sc-a{ } .d{ -webkit-animation:keyframe_880 1s both; animation:keyframe_880 1s both; } @-webkit-keyframes keyframe_144{ from{ opacity: 1; } } @keyframes keyframe_144{ from{ opacity: 1; } } .sc-b{ } .c{ -webkit-animation:keyframe_144 1s both; animation:keyframe_144 1s both; }
+@-webkit-keyframes keyframe_880{ from{ opacity: 0; } } @keyframes keyframe_880{ from{ opacity: 0; } } .sc-a{ } .d{ -webkit-animation:keyframe_880-d 1s both; animation:keyframe_880-d 1s both; } …
```

Upgrade to stylis 3.2 and use constructor

---

package.json

I've changed to build scripts to stop transpiling and publishing the test files
- these files aren't actually used for tests (you're using `jest`)
- these files make the package take longer to install
- these files are inconsistent by distributing the tests for a single target (e.g. there no tests published for `es` or `umd`)
- these files force me to ignore `node_modules/styled-components` unless I `flow-typed install jest`

stopped transpiling and publishing tests

---

README.md

Thought it might make sense to link to a couple more styled-components-based libraries. Happy to change the order and placement however you prefer. 😎 
Also note: I'm seeing failing tests locally, which I'm assuming are not related to the changes here – they appear to be related to vendor prefix differences

Add links to Rebass and styled-system in README.md

---

README.md

>- [styled-shortcuts](https://github.com/donavon/styled-shortcuts): The easiest of the "props helpers". Use simple string notation to access props. No functions necessary! Example: `font-size: ${'theme.fontSize:px'};` ([CodeSandbox](https://codesandbox.io/s/jRE0XxR9v))

Add `styled-shortcuts` to readme under Helpers

---

package.json
typings/styled-components.d.ts
typings/tests/main-test.tsx
typings/tests/themed-tests/mytheme-styled-components.tsx
typings/tests/themed-tests/with-theme-test.tsx
typings/tests/with-theme-test.tsx
yarn.lock

This PR slightly improves typings for TypeScript of `withTheme` HOC.
The issue with previous definitions was in the fact that TypeScript did not allow removing required property from a generic type. However, that is exactly what `withTheme` does with a component's contract. It takes a component that **needs** `theme` prop (encoded as a required prop in the component) and makes another component that simply gets the theme from the context, so basically it removes it from the contract. Following the implementation logic, `theme` is not really removed, it's being made optional (because a consumer can override the theme by passing it directly as a prop).
To work this constraint around, previously we used `theme` defined as an optional, which is obviously not what we wanted. Now, you can see …

Improve TypeScript typings for withTheme HOC

---

README.md

>- [styled-shortcut-components](https://github.com/donavon/styled-shortcut-components): A convenience package that wraps `styled-components` with `styled-shortcuts`.

Add styled-shortcut-components to readme

---

CHANGELOG.md
rollup.config.js
src/models/BrowserStyleSheet.js
src/models/ServerStyleSheet.js
src/test/__snapshots__/ssr.test.js.snap
src/test/ssr.test.js
src/test/styles.test.js

feat: __webpack_nonce__ support in SSR + Browser contexts

---

CHANGELOG.md
src/models/StyledComponent.js
src/test/expanded-api.test.js

Will fix #1031
I added a test with the new behaviour. This should fix server-side rendering issues with `.extend` and `.withComponent`.

Add .extend and .withComponent deterministic ID generation

---

typings/styled-components.d.ts
typings/tests/issue1068.tsx
typings/tests/themed-tests/issue1068.tsx

This PR fixes #1068 and maybe others related
The main cause was in the fact that React's stateless functional components are contravariant on their prop types. And when the previous constraint `P extends { theme?: T; }` was not met by new aggressive exceed property checks, TypeScript fell back to the constraint itself which only had optional fields, and because of contravariance they were structurally assignable.
This PR improves typing of `styled` making class components special case and working around exceed property check for stateless functional components.

Fix for 1068

---

rollup.config.js

Rollup was failing because some plugin was trying to import `package.json` as a javascript module, which obviously threw a syntax error.
Fixed by moving `json()` above the other plugins.

Fix rollup build failing

---

CHANGELOG.md
rollup.config.js
src/models/StyledComponent.js

Aims to fix #1135 
I found one usage of `typeof process` (should there be more?)
Changed the rollup config to only replace and shim process in production

Thorough minification

---

CHANGELOG.md
src/utils/domElements.js

Right now we can add `marquee` tag using `styled('marquee')`.
With this, we can use it by `styled.marquee`
/cc @philpl

Add Marquee tag to default attributes list

---

CHANGELOG.md
src/test/props.test.js
src/utils/flatten.js

This implements #1110.
Note that the output still includes spurious `;`, I have no idea where they come from, I even searched the code for all `;` :)

flatten: ignore falsy non-0 css values

---

README.md

The TypeScript styled plugin adds styled component string error reporting and IntelliSense to VS Code, Sublime, and Atom

Add link to the TypeScript styled plugin

---

CHANGELOG.md
src/models/StyledComponent.js
src/models/StyledNativeComponent.js
src/utils/determineTheme.js

This logic was being repeated in two places, and it looks like we want to place similar logic into the withTheme HOC (see [#1130](https://github.com/styled-components/styled-components/issues/1130).
I'd like some feedback on this before I further generalize it for withTheme.

Extract theme logic from StyledComponent lifecycle methods

---

README.md

npm now saves dependencies by default so --save is no more needed

Minor change in readme

---

CHANGELOG.md
package.json
yarn.lock

Closes #1247 
Fixes #1218 
I think there was something about the "3.x" syntax that was causing this subdependency from being automatically updated externally.
In my own projects, when running `npm update` I have not been getting automatic stylis updates as they are released.

deps: upgrade stylis

---

CONTRIBUTING.md
CORE_TEAM.md

As we are discussing your [guideline improvements](https://github.com/styled-components/styled-components/pull/1364) in the [Moya organisation](https://github.com/Moya/contributors/issues/19), I read through the changes and saw a typo and styling issues, so I fixed them. 😇
There were two main questions I still had after reading both `CONTRIBUTING.md` and `CORE_TEAM.md`; which I want to let you know of - and we'll probably be discussing these over at Moya too:
- Why do you specifically state that the beginning of the process of becoming a core team member should happen privately? I think it would help if there would be an explanation as to why you'd not want this to happen publicly.
- I think it would be a good idea to think about how a core team member can step down - and document it. I …

Fix some typos and improve styling in docs

---

README.md

I have removed the Syntax-highlighting setup from the README.md as it's been added to the website.

Removed syntax-highlighting from REAMD.md

---

CHANGELOG.md
src/models/StyledComponent.js

the execution order of files can differ between build environments
and lead to mismatching hashes. if the babel plugin is being used, we
will usually have a displayName, which will be unique enough for hashing
purposes and we can fall back to the numerical way of doing things as
a fallback
I tested this out in the sandbox and it didn't appear to break anything.
Related: https://github.com/styled-components/babel-plugin-styled-components/issues/105

use a simpler hashing strategy when possible 

---

CHANGELOG.md
src/models/ThemeProvider.js
src/models/test/ThemeProvider.test.js

**What**:
This fixes a bug when having nested `ThemeProvider`s and updating outer theme the change is not reaching the `StyledComponent`
```jsx
<ThemeProvider theme={{}}>
<ThemeProvider theme={{}}>
<StyledComponent>
</ThemeProvider>
</ThemeProvider>
```
**Why**:
This is a bug fix.
**How**:
Using publish in the nested `ThemeProvider`s subscriptions.
**Checklist**:
Repro provided by @mitchellhamilton - https://codesandbox.io/s/w7y56yznj7

Fixed nested themes not being republished on outer theme changes

---

CHANGELOG.md
src/index.js

Yes, it's 2:15am and yes, I've made this mistake too many times than I'm comfortable with admitting 😛 
It's a basic warning on React Native to import `styled-components/native` instead of `styled-components`.
I had some trouble running this locally in order to verify that it works as intended however I assume that this should be ok?

Add warning if importing Web Styled Components on React Native

---

CHANGELOG.md
src/index.js

Current check if `navigator` exists in `master` branch breaks styled-components in node env with `ReferenceError: navigator is not defined`
Probably this should be covered with tests somehow, but I'm not sure how. I tried to change imports in `ssr.test.js` from `import ServerStyleSheet from '../models/ServerStyleSheet'` to `import { ServerStyleSheet } from '../index'`, but after that all tests started to fail with `Invariant Violation: StyleSheetManager.getChildContext(): key "__styled-components-stylesheet__" is not defined in childContextTypes.` and I have no clue where this error is coming from 😿

Change navigator check to prevent crashing in node env

---

CORE_TEAM.md

Due to his amazing contributions over the past months and clear understand of the styled-components vision we decided to invite Evan to the core team. To our joy, he's accepted the invitation, so please welcome the newest member of our core circle: [@probablyup](https://twitter.com/probablyup)! 🎉🎊

Add @probablyup to the core team

---

CHANGELOG.md
src/hoc/withTheme.js
src/test/theme.test.js

Fixes the warning that sometimes occurs when using `withTheme`. Currently, when `shouldSetInnerRef` is `false`, it adds `innerRef` as `undefined` when it should not add it at all. 
If I try to use `{...this.props}` inside the component, it produces this error:
```
Warning: React does not recognize the `innerRef` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `innerref` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

Inner ref fix

---

CHANGELOG.md
src/index.js
src/native/index.js
src/primitives/index.js

Expose `isStyledComponent` utility as a named export. This functionality is useful in some edge cases, such as knowing whether or not to use `innerRef` vs `ref` and detecting if a component class needs to be wrapped such that it can be used in a component selector.

expose isStyledComponent utility

---

.eslintrc
.prettierrc
CHANGELOG.md
src/constructors/constructWithOptions.js
src/constructors/keyframes.js
src/hoc/withTheme.js
src/index.js
src/models/BrowserStyleSheet.js
src/models/ComponentStyle.js
src/models/InlineStyle.js
src/models/ServerStyleSheet.js
src/models/StyleSheet.js
src/models/StyledComponent.js
src/models/StyledNativeComponent.js
src/models/ThemeProvider.js
src/native/index.js
src/no-parser/flatten.js
src/no-parser/index.js
src/no-parser/stringifyRules.js
src/primitives/index.js
src/types.js
src/utils/createWarnTooManyClasses.js
src/utils/flatten.js
src/utils/interleave.js
src/utils/stringifyRules.js
src/utils/validAttr.js

They're not supported in ES5, which is tested against in the node
versions included by the styled-components CI. Also disabled an
eslint rule that was conflicting with what prettier was doing.

remove trailing commas for functions

---

src/test/attrs.test.js

This PR should fix React 16 warning:
Having a mission to "eradicate red from tests" I traced these guys:
Unfortunately, they are coming from imports of `StyleSheet` and `View`. Related fixes already landed on react-native master branch and should be a part of upcoming version 0.52
- https://github.com/facebook/react-native/commit/50b11aa09b479e5ce8b06de98e02ba1dd6a8cca3#diff-00341ed486de763a230150ede8084f57R15
- https://github.com/facebook/react-native/commit/9afb71fde8199156ed683dca6aa59826f9fb9279#diff-a562e4a7ac9e900c6d2bc644453e9152R77

fix: console error in attrs test

---

typings/styled-components.d.ts
typings/tests/component-type-test.tsx

This simplifies the typing of `styled` and allows passing it a `React.ComponentType<P>`. Adds a very simple test case that checks the same thing as #1420 but without the need to depend on all of `material-ui`.
Resolves #1420.
Resolves https://github.com/mui-org/material-ui/issues/9838.

Allow ComponentType to be passed to styled

---

package.json
rollup.config.js
scripts/rollup-plugin-ignore.js
yarn.lock

This fixes our windows build which previously failed due to rollup-plugin-hypothetical.

Replace rollup-plugin-hypothetical with custom ignore plugin

---

CHANGELOG.md
src/models/ServerStyleSheet.js

fixes a bug where the last tag might end up getting emitted multiple times due to an off-by-1 issue

simplify stream emitter code

---

CHANGELOG.md
src/models/BrowserStyleSheet.js
src/models/ServerStyleSheet.js
src/models/StyleSheet.js

1. on rehydration when SPEEDY is on, certain CSS selector characters were getting HTML entity-ifed due to usage of `innerHTML`
2. fix a streaming edge case when additional styles are appended to an existing element whose tag was already emitted

fix a few bugs 

---

package.json
typings/styled-components.d.ts
typings/tests/server-test.tsx
typings/tests/tsconfig.json
yarn.lock

This is a small change that adds TypeScript definitions for `ServerStyleSheet`'s `interleaveWithNodeStream` and the `consolidateStreamedStyles` methods.
One important thing to note is that there was a need to install the `@types/node` module to access the `NodeJS.ReadableStream` type, which is what `react-dom/server`'s `renderToNodeStream` returns. The TypeScript node definition conflicts with that of `react-native` because they both globally declare different require methods. For this reason, I had to set `skipLibCheck` to false in the tsconfig file.
For more information on the conflict:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16825

Typescript SSR Stream support

---

CHANGELOG.md
src/constructors/constructWithOptions.js
src/constructors/injectGlobal.js
src/constructors/keyframes.js
src/vendor/glamor/hash.js

- Avoid destructuring the tagged template function arguments, which should also help performance a tiny bit
- Replace murmurhash implementation (That's the best one for JS imho; The commit message has a link showing that they yield the same results btw)

Refactor to shave off a couple of bytes from bundle

---

.github/ISSUE_TEMPLATE.md

This is a partial solution to https://github.com/styled-components/styled-components/issues/1584
Here is a sample of the environment report that will envinfo will provide:
tabrindle-mbp:ap2-client tabrindle$ npx envinfo --markdown --clipboard --system --binaries --npmPackages styled-components,babel-plugin-styled-components
- OS: macOS High Sierra 10.13
- CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
- Free Memory: 656.37 MB
- Total Memory: 16.00 GB
- Shell: /usr/local/bin/bash - 4.4.12
- Node: 8.9.4
- Yarn: 1.3.2
- npm: 5.6.0
- Watchman: 4.9.0
- Docker: 17.12.0-ce, build c97c6d6
- Homebrew: 1.5.8
- wanted: ^3.1.6
- installed: 3.1.6

add envinfo command to issue template

---

package.json

As we can see in opencollection documentation https://github.com/opencollective/opencollective-postinstall#install, for correct work in production "exit 0" should be added to postinstall script.
Without this case sometimes styled-components produces an error:
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! styled-components@3.2.0 postinstall: `opencollective postinstall`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the styled-components@3.2.0 postinstall script.

Add support for correct execution of postinstall script

---

CHANGELOG.md
package.json
src/test/basic.test.js
yarn.lock

Resolves #1576 
This will simply upgrade to stylis@^3.5.0 and stylis-rule-sheet@^0.0.10
See: https://github.com/thysultan/stylis.js/issues/99
And: https://github.com/thysultan/stylis.js/blob/master/CHANGELOG.md#350-march-08-2018

Upgrade stylis & stylis-rule-sheet to fix nested at-rules

---

package.json
yarn.lock

Just noticed recently in the project I'm using that `static getDerivedStateFromProps` is not being hoisted by `withTheme` and bumping `hoist-non-react-statics` fix it, because it's now supported. Hopefully it doesn't break any tests 😅.

Bump hoist-non-react-statics to support React 16.3

---

CHANGELOG.md
src/constants.js
src/test/constants.test.js

This PR will fix https://github.com/styled-components/styled-components/issues/1032
I have similar problem when embedding our widget to sites using styled-components.
Even when StyleSheetManager used inside iframe for isolating styles, styled-components inserts empty `<style />` into main `window.head`. As @prevostc mentioned, providing custom `SC_ATTR` fix conflict and styles no longer break.

Add ability to change SC_ATTR via process.env

---

.travis.yml
appveyor.yml
package.json
scripts/postinstall.js
yarn.lock

Some minor refactors of our scripts while I was at it:
- Swap `prepublish` with `prepublishOnly` (let's please not build on every install)
- Use `npm-run-all` where appropriate for some simplification
And what this is actually about:
- Remove `opencollective` cli package
- Add small `postinstall.js` script into `scripts/` folder
The message fulfils a couple of our new criteria:
- It's short
- It has no annoying colours or emoji since some ppl dislike that
- It's not pushy, but personal
- It just asks ppl to take a look (~donate~, ~support~)
The message reads as such:
> Take a look at https://opencollective.com/styled-components/donate to help out styled-components’ maintainers
Removing the opencollective dependency is quite important as it turns out (See #1644, #1628) as it introduces …

Replace opencollective postinstall message

---

CHANGELOG.md
package.json
src/models/ComponentStyle.js
src/models/test/StyleSheetManager.test.js
yarn.lock

Fixes #1634, Whitespace-change free version of PR #1635
When ComponentStyle.generateAndInjectStyles is invoked, the stylesheet instance should be checked even if the style name is already defined. If the component is being rendered in a sibling iframe with a separate StyleSheetManager, this allows the second iframe to receive the injected styles.

Fix ComponentStyle caching strategy to take StyleSheet cache into account

---

typings/styled-components.d.ts

Current [home page](https://www.styled-components.com) example shows this code.
```js
const Button = styled.a`
....
/* The GitHub button is a primary button
* edit this to target it specifically! */
${props => props.primary && css`
background: white;
color: palevioletred;
`}
`
```
This PR makes it type-check in TypeScript with `strictNullChecks` on. Right now type-checking fails with:
```
src/sample.tsx(72,7): error TS2345: Argument of type '(props: { primary: boolean; }) => false | InterpolationValue[]' is not assignable to parameter of type 'Interpolation<ThemedStyledProps<ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement> ...'.
Type '(props: { primary: boolean; }) => false | InterpolationValue[]' is not assignable to type 'ReadonlyArray<string | number | Styles | …
```

Include falsey values in InterpolationValue

---

CHANGELOG.md
src/models/ComponentStyle.js

Found this little guy when browsing the codebase.

fix: typo copmonent => component

---

CONTRIBUTING.md

Since this repo contains `yarn.lock` but not `package-lock.json`.

Update setup guide to use `yarn` instead of `npm`

---

CHANGELOG.md
package.json
src/models/StyledNativeComponent.js
src/native/test/native.test.js
src/primitives/test/primitives.test.js
yarn.lock

Using a `React.createRef()`-created ref as `innerRef` would break under `react-native` (but not react-dom) as `StyledNativeComponent` (unlike `StyledComponent`) is already using `ref` and didn't know how to forward to the new type.
AFAIK, primitives didn't have the same issue, but I updated the test there, since they were copy pasted. I attempted to add tests for `react-dom`, but ran into what looks like an `enzyme` bug, see the follow-on #1720 for more details.
Also, I had to test under jest 22 on my machine for some reason - jest 20 just hung on (at least) test:native? I avoided including that change here.

Add createRef() tests, fix for react-native.

---

CHANGELOG.md
src/utils/insertRuleHelpers.js

See [here](https://github.com/styled-components/styled-components/pull/1493#issuecomment-390716273) for more info.

Fix off-by-one error in insertRuleHelpers.js

---

typings/styled-components.d.ts

Fixes #1758
Partial rollback of change in #1711
See issue for explanation of why it is necessary

Fix `innerRef` types not handling null

---

.travis.yml
typings/styled-components.d.ts

this change is a port of #1773 for 2.x. It is required for v2 users (I am one of these) to upgrade to TS 2.9.
I think we can make a patch release 2.4.1.
Supersedes #1774

[v2] Make TypeScript definition compatible with TS 2.9.1

---

typings/styled-components.d.ts

This is a minor fix that makes TS typings work on older and the latest version of TypeScript (up to 2.9.1).
Should supersede #1771 and fix #1772.
This is a non-breaking change, so can be released as a patch.

Make TypeScript definition compatible with TS 2.9.1

---

typings/styled-components.d.ts

This change is a workaround for TypeScript issue (Microsoft/TypeScript#24449) that prevents passing type argument to tagged template.
The workaround is simply consolidating overloads into one.
With this PR and TypeScript 2.9.1 it will be possible to write:
```ts
const Title = styled.h1<{ size: number }>`
font-size: ${p => p.size}em;
`
```
and it will be fully type-safe,
Addresses #630

Allow TypeScript 2.9.1 accept tagged template type argument

---

typings/styled-components.d.ts
typings/tests/issue1068.tsx
typings/tests/themed-tests/issue1068.tsx

Fixes #1804
Calling `styled()` with a component whose props have an index signature, results in a component with no props besides `theme`.

[TypeScript] Fix: Diff removes props from indexed prop types

---

CHANGELOG.md
src/models/StyledComponent.js
src/models/StyledNativeComponent.js
src/test/__snapshots__/extending.test.js.snap
src/test/extending.test.js

Fixes #1781
The `extend` and `withComponent` statics are getting hoisted and fubaring things since they rely on closure variables. Fixed that and switched to the [third arg way of excluding things from `hoist`](https://github.com/mridgway/hoist-non-react-statics#usage), which is easier to understand and probably will be easier to maintain.

fix regression when extending a styled(StyledComponent)

---

CHANGELOG.md
src/constructors/css.js
src/test/basic.test.js
src/types.js

Closes #1620
Inspired by @probablyup's comment, I checkout out #1732 to see if I could solve my problem in #1620. Turns out, it was really straightforward.
To get a feel for the syntax this enables:
or alternatively
This is particularly useful for DRYing up repetitive logic mapping props to styles and not having to repeatedly reference the props object.

add support for first-class functions

---

typings/styled-components.d.ts
typings/tests/is-styled-component-test.tsx

Hey there 👋
Just noticed `isStyledComponent` helper function is missing from `.d.ts` typings. Hope that signature is correct 😅.

chore: add missing typings for `isStyledComponent`

---

typings/styled-components.d.ts
typings/tests/issue1821.tsx
typings/tests/themed-tests/issue1821.tsx

This fixes #1821 by reverting #1798.
Please note, that new syntax that was allowed by #1798 is still allowed but requires TypeScript 2.9.2 which fixed overload resolution.

[TypeScript] Fix #1821

---

benchmarks/src/implementations/styled-components/Dot.js

For some reason this was built using `.attrs`, which skewed the update dynamic styles benchmark. This PR switches it back to props interpolations.
~~EDIT: This actually crashes the update dynamic styles benchmark! :scream: We should probably fix that performance...~~ Nevermind I'm just a dummy.
Here are the new results that accurately reflect lib speed:

Switch from .attrs to interpolations in benchmarks

---

CHANGELOG.md
src/models/StyleSheet.js
src/test/styles.test.js

Fix #1890 
A regression was introduced and not caught in time in #1843 which has gone out recently.
What happens is:
- Components are created and call `deferredInject` on a `StyleSheet`
- Some clones are created from StyleSheet.master which inherit all deferred arrays
- The prior two steps might also be in reverse order; doesn't matter
- `inject` is called on render which takes deferred rules into account
- During the injection the `deferred[id]` array is mutated (to avoid `concat`)
- The mutated array is then used in the same manner in other stylesheets, which add the rules that need to be injected again
Hence the outcome is that rules are duplicated for each subsequent clone that injects them.

Fix rule-injection with deferred rules being mutated while used across clones

---

CHANGELOG.md
package.json

It's been superceded by "module"
Closes #1825

remove jsnext:main package.json entry point

---

.flowconfig
rollup.config.js

Frustrating, but because rollup doesn't have an internal concept
of prod vs dev, it doesn't set NODE_ENV accordingly and babel
uses the same config for everything. So we are able to eliminate
the references to prop types, but the module import itself is not
being eliminated without this change.

fix removal of PropTypes import in production builds

---

integration-test/styled-components-no-tags.test.js
no-tags/package.json
package.json
rollup.config.js
src/base.js
src/index-without-tags.js

This allows babel users to drop the element whitelist and save some bytes.
Related to https://github.com/styled-components/babel-plugin-styled-components/issues/125

add "no-tags" entry to be used in conjunction with babel plugin

---

.flowconfig
example/devServer.js
example/example.js
example/index.html
integration-test/jest-styled-components.test.js
integration-test/styled-components-no-tags.test.js
rollup.config.js
src/index-standalone.js

something about the "umd" setting in recent versions of rollup
just doesn't work properly
verified this fixes things as expected and allows browser users to not have to do `styled.default` anymore: https://codesandbox.io/s/9q3pm157jw
closes #1870

fix standalone browser build

---

src/constructors/keyframes.js
src/constructors/test/keyframes.test.js
src/models/ComponentStyle.js
src/models/Keyframes.js
src/test/rehydration.test.js
src/types.js
src/utils/flatten.js

Re-implement code from https://github.com/styled-components/styled-components/pull/1700 which ideas was taken from https://github.com/styled-components/styled-components/issues/1496
Based on current develop branch (I hope to ship this with 4.0 together with new global styling API)
Changelog:
- keyframes`` helper  now returns Keyframes model
- keyframes styles now inserting only with component rendering
- To get animation name use `.getName()` method
- some tests was changed to proper work with new `keyframes` helper

Keyframes refactoring

---

src/models/StyledComponent.js
src/models/StyledNativeComponent.js

In production mode, the function was undefined. This change makes it a noop when `NODE_ENV=production`.

Fix undefined warnExtendDeprecated call in production mode

---

src/constructors/createGlobalStyle.js

React 16 seems to wait to unmount in some cases, which was causing
a false-positive warning to go out when there was realistically only
one instance of cGS live on the page.
Should fix the issue discussed here: https://github.com/styled-components/styled-components/issues/1969#issuecomment-419715411

adjust when the cGS multicompose warning is fired

---

src/test/ssr.test.js

Issue #1982 
I add this test for SSR multi chunked streaming.
As I mentioned the issue, I think it should pass, but it was failed (v3.4.5). 
Following `received` stream data do not contain the style for `Footer`.
If you add this 1 line, this test succeeded.
ServerStyleSheet instance property `tagMap` might have unneeded data.
```
const sheet = new ServerStyleSheet()
+   sheet.instance.tagMap = {}
const jsx = sheet.collectStyles(
```

Add SSR chunked streaming test

---

package.json

To my knowledge this is true now, given that all our helpers and
API methods create objects that must be used a second time in
JSX.

mark the library as side-effect-free

---

CHANGELOG.md
src/constructors/injectGlobal.js

The warning about the removal of `injectGlobal` was removed in #1909 because the PR about the removal (#1867) was not yet merged. This was done about two weeks ago so I thought it might make sense to re-add the warning again.
This is simply a copy and paste of the initial version from #1909 with adapted wording.

Add warning for the removal of injectGlobal in v4

---

src/models/test/StyleSheetManager.test.js

Rebased test from https://github.com/styled-components/styled-components/pull/1194
Now test passes which means bug with ordering no longer exists

Add test for correct rendering order

---

CHANGELOG.md
src/constructors/createGlobalStyle.js
src/constructors/test/__snapshots__/createGlobalStyle.test.js.snap
src/constructors/test/createGlobalStyle.test.js
src/models/GlobalStyle.js
src/models/StyleSheet.js
src/test/rehydration.test.js
src/test/ssr.test.js
src/utils/errors.md

This was a really weird one. I still don't know why this works,
but it does and it's the only impl that did.
Fixes the issue noted here: https://github.com/styled-components/styled-components/issues/1969#issuecomment-421142583

fix cGS + HMR

---

src/models/StyledComponent.js
src/models/StyledNativeComponent.js
src/utils/errors.md

Once the devtools forwardRef displayName PR is merged, the output should look a little more tidy

rename base component to make devtools tree nicer

---

CHANGELOG.md
src/constructors/createGlobalStyle.js

Someone suggested putting the count increment in cDM but that doesn't
work since the styles are injected on render and renders can happen
without cDM ever being called.

reapply my original cGS HMR change

---

src/constructors/injectGlobal.js

RE: https://github.com/styled-components/styled-components/issues/1333#issuecomment-422370844
Use `console.warn` instead of `console.error`  for `injectGlobal` deprecation notice.

Tone down dev warning for deprecated injectGlobal

---

.flowconfig
src/constructors/createGlobalStyle.js
src/constructors/keyframes.js
src/constructors/test/createGlobalStyle.test.js
src/models/ComponentStyle.js
src/models/GlobalStyle.js
src/models/InlineStyle.js

~~I'm not sure if this is the right solution. Ideally we wouldn't run the `css` helper until render time but since we're hashing the completed rules I'm not sure if that can be changed.~~ It wasn't. But the PR has been updated to the correct solution.
Fixes #2027

fix createGlobalStyles + keyframes

---

src/constructors/keyframes.js

Helper `keyframes` cannot be used on React Native, so we should add a corresponding warning.
https://github.com/styled-components/styled-components/pull/2029#issuecomment-423969660

Add warning when using `keyframes` on React Native

---

CHANGELOG.md
src/hoc/test/withTheme.test.js
src/hoc/withTheme.js
src/utils/determineTheme.js
src/utils/test/determineTheme.test.js

Updated withTheme to take default props from WrappedComponent. Fixes issues when ThemeProvider is not used but theme is defined in defaultProps.

fixed withTheme

---

CHANGELOG.md
test-utils/index.js

Helps us get around the issue with enzyme not displaying forwardRef displayName for the time being.

add enzymeFind test-util

---

CHANGELOG.md
src/models/StyledComponent.js
src/test/__snapshots__/expanded-api.test.js.snap
src/test/expanded-api.test.js
yarn.lock

Support for as utility in attrs

---

scripts/postinstall.js

without it some terminals dont understand that it is a link.
When they do it is very convenient to just click on it see what's there.
Perhaps it can drive up the conversion of donations (I hope it does at least a little bit)

add protocol to open collective link

---

CHANGELOG.md
src/utils/flatten.js
src/utils/test/flatten.test.js

#2053 
Hello, i think i made a fix for showing right warning message.
Please feel free to suggest better error message :)

Add warning for non styled components

---

.travis.yml
CHANGELOG.md
src/models/ComponentStyle.js
src/test/styles.test.js
src/utils/stringifyRules.js

When a component refers to itself with the ampersand placeholder the behavior today is a bit inconsistent and won't work as intended if your component has dynamic styles.
For example:
```jsx
const Comp = styled.div`
color: ${p => p.color};
& + & {
margin-left: 10px;
}
`;
<div>
<Comp color="red">Hello</Comp>
<Comp color="blue">World</Comp>
</div>
// renders
// <div>
//   <div class="sc-a a">Hello</div>
//   <div class="sc-a b">Hello</div>
// </div>
```
The second instance of `Comp` will not get the `margin-left` because a different className is generated due to the different color prop, and today ampersand refers to the current styling context  className.
It effectively looks like this:
```css
// Comp -> .sc-a
// color: red -> .a
// color: blue -> .b
.sc-a {}
.a { color: red }
.a + .a { …
```

fix self-referential behavior in combo selectors

---

CHANGELOG.md
src/models/StyledComponent.js
src/test/basic.test.js
src/utils/classNameUseCheckInjector.js

https://github.com/styled-components/styled-components/issues/349
I tried several options like using getters/Proxy but it doesn't work because of copying props inside React (https://github.com/facebook/react/blob/master/packages/react/src/ReactElement.js#L193)
Proposed code warns in such cases:
```js
const Test = () => <div />;
const StyledTest = styled(Test)`
background: white;
`;
<StyledTest />
```
and doesn't warn in such cases:
```js
const Test2 = ({ className = '' }) => (
<div>
<div className={className} />
</div>
);
const StyledTest2 = styled(Test2)`
background: black;
`;
<StyledTest2 />
```
Tested with webpack 4: classNameUseCheckInjector.js will not present in bundle in production mode.

Add warning when className prop is not used

---

CHANGELOG.md
src/utils/classNameUseCheckInjector.js
src/utils/test/classNameUseCheckInjector.test.js

Adding, e.g., `className="foo bar  "` caused the `classNameUseCheckInjector`
to build a selector with multiple dots (`.foo...bar`) which causes an error
in Chrome. This commit changes the classNames to be trimmed and excess spaces
removed before the selector is constructed.
Error could be something like the following:
```
Error: Failed to execute 'querySelector' on 'Element': '.foo.bar...sc-bwzfXH.hHwLpk' is not a valid selector.
```

fix error caused by repeated spaces in className

---

package.json

bundlephobia can't process the library without it explicitly
marked

add react-dom as a peerDep

---

src/constructors/test/keyframes.test.js
src/models/Keyframes.js
src/utils/errors.md

This will now throw an error, prompting the user to use the css\`\`
helper as is required in v4 (but wasn't in v3):
```
const rotate = keyframes``
const styles = `
animation-name: ${rotate};
`
```

Add error to keyframes when interpolated into raw string

---

CHANGELOG.md
src/constructors/createGlobalStyle.js
src/constructors/test/createGlobalStyle.test.js

This PR fixes #2082 by adding a warning to disable warning when `suppressMultiMountWarnings` prop is added. @probablyup Adding styles for all the instances of the component seems to be a bit hard to do right now. Is the warning enough or should we make the components add multiple styles for the CGS component?

Add suppressMultiMountWarnings prop to disable warning on multiple cgs mount

---

src/test/styles.test.js

Since beta 11 of Styled Components `4.0.0`, we've been experiencing a regression where some selectors that use the ampersand operator will not be properly converted.
Input:
```
.foo > & {}
```
Expected output:
```
.foo > .x {}
```
Actual output:
```
.x .foo > .x {}
```
The culprit appears to be this regular expression: https://github.com/styled-components/styled-components/blob/12cde61a9bb6dbbd167cbb2b3244c1354b32d566/src/utils/stringifyRules.js#L7
Unfortunately, I don't think I have enough context to fix this without breaking other things that depend on it.

Failing test for ampersand selector

---

CHANGELOG.md
src/base.js
src/models/ThemeProvider.js

This PR attempts to fix #2148 
The fix is to expose `ThemeContext` object for use as `contextType`

Expose ThemeContext to enable static contextType support for React 16.6

---

CHANGELOG.md
src/utils/classNameUseCheckInjector.js
src/utils/test/classNameUseCheckInjector.test.js

Related to https://github.com/styled-components/styled-components/issues/2126, https://github.com/styled-components/styled-components/pull/2073

Add `suppressClassNameWarning` prop to supress classNames usage warnings

---

CHANGELOG.md
src/models/StyledComponent.js
src/models/StyledNativeComponent.js
src/native/test/native.test.js
src/test/attrs.test.js

Adds a warning if a component is used as an `attrs` prop, as discussed in #2117.

Warn if result of `attrs` prop function is an element

---

CHANGELOG.md
src/models/StyledComponent.js

I'm not sure if this breaks anything, but if it doesn't it might prevent some unnecessary re-renders?

Avoid subscribing static components

---

CHANGELOG.md
src/constants.js
src/test/constants.test.js

This is, if nothing else, a temporary fix until #2167 is resolved.
Currently, using Percy doesn't work for my company. We are using `styled-components` within a `create-react-app` app, which doesn't allow its users to override `NODE_ENV` for builds.
This PR allows a global `SC_DISABLE_SPEEDY` variable to be set before `styled-components` is imported. For my company, this would look something like this:
```html
<script>SC_DISABLE_SPEEDY=/percy/.test(location.host)</script>
<script src="/main.js></script>
```
#2038
#2089

add SC_DISABLE_SPEEDY runtime override

---

.eslintrc.json
.jest.native.json
.jest.primitives.json
.jest.web.json
CHANGELOG.md
package.json
rollup.config.js
src/constants.js
src/constructors/constructWithOptions.js
src/hoc/test/withTheme.test.js
src/hoc/withTheme.js
src/models/ComponentStyle.js
src/models/GlobalStyle.js
src/models/StyleSheet.js
src/models/StyledComponent.js
src/models/StyledNativeComponent.js
src/native/test/native.test.js
src/primitives/test/primitives.test.js
src/test/__snapshots__/attrs.test.js.snap
src/test/attrs.test.js
src/test/constants.test.js
src/types.js
src/utils/isStaticRules.js
src/utils/once.js
yarn.lock

attrs is now implemented as an array internally to make it
easier to do merging etc and handle different types of things
passed in
Closes #1171 
This is an alternate implementation of https://github.com/styled-components/styled-components/pull/2176 that will allow more & easier customization in the future (and is smaller.)

allow attrs to be called with a function

---

CHANGELOG.md
src/native/index.js
src/primitives/index.js

add ThemeConsumer & ThemeContext exports to RN, primitives entries

---

CHANGELOG.md
src/models/StyledComponent.js
src/models/StyledNativeComponent.js
src/test/__snapshots__/attrs.test.js.snap
src/test/__snapshots__/expanded-api.test.js.snap
src/utils/classNameUsageCheckInjector.js

fixes #2232
this allows for interim components that have been folded to still
be targeted

 inject static classnames from folded components

---

src/test/overriding.test.js

As desired in the bug report guidelines, I created a PR showing what's not working.
Chaining `styled` and `withComponent` breaks the props of the original component. I created some unit tests showing that it works without `withComponent` and breaks with `withComponent` if it's a child of a child of a parent component.

Tests for Bug: Not working props in nested inheritance

---

CHANGELOG.md
src/test/basic.test.js
src/utils/generateDisplayName.js
src/utils/getComponentName.js
src/utils/isTag.js

It's very common to write tests like this:
```jsx
jest.mock("../SomeComponent", () => "MockedComponent");
it("test", () => {
expect(testRenderer(<Component someParam="a" />)).toMatchSnapshot();
});
```
where ```Component``` may be:
```jsx
import SomeComponent from "./SomeComponent";
export default styled(SomeComponent)` /* stuff */`;
```
In this case ```SomeComponent``` becomes string-typed internally similar to dom-like components and only name with passed props is being rendered is snapshots.
Without this fix, the ```styled-components``` thinks as ```SomeComponent``` is like dom-like component and applies props filtering to it, resulting in filtered out custom props (```someParam``` in example above) from test snapshots.

isTag() additionally check for casing of the first char

---

src/macro/index.js
src/macro/test/__snapshots__/macro.test.js.snap
src/macro/test/macro.test.js

This is unnecessary, as the import name is already guaranteed to be unique. By not rewriting the import name, we can make the Babel plugin css prop work with the macro!
Before:
```JS
import styled from 'styled-components/macro';
// Before this was turned into
import _styled from 'styled-components';
// Now it's turned into
import styled from 'styled-components';
```
/cc @satya164

Don't generate a UID name from the macro for the import

---

CHANGELOG.md
src/constants.js
src/test/constants.test.js

Creating this PR to replace #2268.
This is cherry picked from #2185 to backport this functionality to v3.
* add `SC_DISABLE_SPEEDY` runtime override
* refactor `SC_ATTR` tests into their own 'describe' section
* add tests for `DISABLE_SPEEDY` and `SC_DISABLE_SPEEDY` global variable
* add `CHANGELOG` entry

Add SC_DISABLE_SPEEDY runtime override for v3

---

CHANGELOG.md
src/constructors/createGlobalStyle.js

This PR ensures the `GlobalStyleComponent` created by `createGlobalStyle` calls the base constructor with `props`.
This is a React best practice for class components:
> Class components should always call the base constructor with `props`.
> — https://reactjs.org/docs/state-and-lifecycle.html#adding-local-state-to-a-class
Not doing so can cause issues with `this.props` being undefined when rendered by libraries that are not very fault tolerant.
React's `renderToString` accounts for it here: https://github.com/facebook/react/blob/v16.7.0/packages/react-dom/src/server/ReactPartialRenderer.js#L532
Apollo's `getDataFromTree` used to account for it here: https://github.com/apollographql/react-apollo/blob/v2.2.4/src/getDataFromTree.ts#L80
Fixes …

Make the GlobalStyleComponent call the base constructor with props.

---

CHANGELOG.md
packages/styled-components/src/utils/domElements.js

`TypeError: styled_components__WEBPACK_IMPORTED_MODULE_8__.default.marker is not a function`
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/marker

Add svg marker tag to domElements.js

---

CHANGELOG.md
packages/styled-components/src/utils/flatten.js
packages/styled-components/src/utils/isStatelessFunction.js
packages/styled-components/src/utils/test/flatten.test.js
packages/styled-components/src/utils/test/isStatelessFunction.test.js

Closes #2424 
If you inspect the issue, you will see there is a major GC collector happening. `flatten` function is called a lot of times and every time we interpolate some style that code block is executed.
I'm avoiding to do `new chunk` and, instead, replaced with a new util called `isStatelessFunction`.

Reduce GC pressure by avoiding to create new object types

---

CHANGELOG.md
packages/styled-components/src/models/StyledComponent.js
packages/styled-components/src/test/basic.test.js

fixes #2346 
Once I tried the solution that @leantide [mentioned in the related issue](https://github.com/styled-components/styled-components/issues/2346#issuecomment-459407874), but it didn't work (I think it is because React likely freezes props). 
What I did Instead is to filter suppressClassNameWarning when passing props to child component.

Filter suppressClassNameWarning to not to pass down to wrapped components

---

packages/styled-components/src/utils/classNameUsageCheckInjector.js
packages/styled-components/src/utils/test/classNameUsageCheckInjector.test.js

Here's a new problem:
At first, I think it's an easy test, just copy the #2080's test and rewrite several words.
But it not works?!
`styled.div` used for two times will break the test. 
I can't understand why, can anyone help me?
And why `renderIntoDocument(components)` return null while components created by styled-components?
Here's my local test result , if I copy the same code, it failed

add test for #2333

---

packages/styled-components/src/models/StyledComponent.js
packages/styled-components/src/models/StyledNativeComponent.js
packages/styled-components/src/native/test/native.test.js
packages/styled-components/src/primitives/test/primitives.test.js
packages/styled-components/src/test/attrs.test.js

Addresses #2481 
I was thinking of `warn` utility that handles all warnings and attach stack trace, but I'm not sure if this will be used for all warnings

Add stack trace to .attrs warning

---

packages/styled-components/src/native/index.js

Using styled-components with react-native-web broke after upgrading to react-native-web 0.11, as they removed the legacy default export, see https://github.com/necolas/react-native-web/releases. This provides a fix by using `import * as` which seems more idiomatic anyways.

Compatibility with react-native-web 0.11

---

packages/styled-components/src/models/StyledComponent.js

attach displayName to forwardRef function as described in React docs

---

packages/styled-components/src/utils/error.js
packages/styled-components/src/utils/test/__snapshots__/error.test.js.snap

Improve error message for `StyledComponentsError` when no additional arguments are provided.
Tiny little thing I found. The variable `interpolations` will always evaluate to true, since `[]` is a truthy value 😄 .

Improve error message for StyledComponentsError

---

CHANGELOG.md
packages/styled-components/src/macro/index.js
packages/styled-components/src/macro/test/__snapshots__/macro.test.js.snap
packages/styled-components/src/macro/test/macro.test.js

Fixes #2378. That issue will mistakenly closed, as the issue lives in the macro, not in the types. I figured providing a solution would help clarify the issue.
I also added a test for multiple imports, as I didn't expect to see them split in the test I wrote, so I wanted to confirm and test that behavior before I added my change.

Fix macro with ts

---

packages/styled-components/src/sheet/Rehydration.js
packages/styled-components/src/sheet/Tag.js

When inserting our CSS text, some CSS will always be invalid for the browser it loads in. So in IE11 some rules, like `-webkit` keyframes will become invalid.
Usually the spec dictates that in such a case the browser should ignore this rule and subsequently exclude it from the style element's `CSSStyleSheet`. In IE11 however there are some cases where it's not excluded.
When such an invalid rule is accessed it behaves incorrectly and when we try to access `cssText` in `Rehydration` it will throw a `Member Not Found` error. This can be prevented by checking the `typeof cssText` first.
Note: This doesn't need to be fixed on `sheet/Tag` but I felt it was safer to add it anyway.

Fix IE11 quirk in canary when accessing cssText

---

CHANGELOG.md
packages/styled-components/src/models/StyledComponent.js
packages/styled-components/src/models/StyledNativeComponent.js
packages/styled-components/src/native/test/native.test.js

Cherry picked the changes in #2567 to the canary branch. Required solving a small merge conflict because of refactoring the same piece of code.

Fix theme prop usage in StyledNativeComponent

---

CHANGELOG.md
packages/styled-components/src/models/StyledComponent.js
packages/styled-components/src/models/StyledNativeComponent.js
packages/styled-components/src/native/test/native.test.js

Modifies determineTheme usage, such that `theme === undefined` is also handled correctly.
This is another PR that fixes #2367, but does more refactoring as suggested in #2558.
I created this as a separate PR, so you can still easily merge #2558 if that is preferred in the end.

Fix #2367 in a cleaner way, but with more refactoring

---

CHANGELOG.md
packages/styled-components/src/models/StyledComponent.js
packages/styled-components/src/models/StyledNativeComponent.js
packages/styled-components/src/native/test/native.test.js
packages/styled-components/src/test/props.test.js

same as the [canary PR](https://github.com/styled-components/styled-components/pull/2573) but this is a simple-enough change that we can ship it in a 4.x minor release

implement forwardedAs for 4.x

---

CHANGELOG.md
packages/styled-components/src/models/StyledComponent.js
packages/styled-components/src/models/StyledNativeComponent.js
packages/styled-components/src/native/test/native.test.js
packages/styled-components/src/test/props.test.js

This works around the most common issue with #439 and #2545  around integrating the `styled()` HOC with other components that also accept an "as" prop

add forwardedAs prop

---

packages/styled-components/package.json
packages/styled-components/src/models/StyleSheetManager.js
yarn.lock

fixes `stylisPlugins` triggering the warning unnecessarily

use shallowequal for equivalency checking instead

---

CHANGELOG.md
packages/styled-components/src/constants.js
packages/styled-components/src/test/constants.test.js

When working with two or more different styled-components instances on a single page (or application), `SC_ATTR` environment variable could be used for distinguishing between those instances.
However, in create-react-app based applications, environment variables are filtered out by matching them with a well-known pattern (`REACT_APP_`) -> [see here](https://github.com/facebook/create-react-app/blob/bffc296a2c8967d46bed40d3120d82f2752496dc/packages/react-scripts/config/env.js#L73).
This PR enables usage of `REACT_APP_SC_ATTR` environment variable as a fallback and its easier configuration via a `.env` file.

Make possible to initialize SC_ATTR via REACT_APP_SC_ATTR env variable

---

CHANGELOG.md
packages/styled-components/src/models/StyledComponent.js
packages/styled-components/src/models/StyledNativeComponent.js
packages/styled-components/src/test/basic.test.js
packages/styled-components/src/utils/isStyledComponent.js
packages/styled-components/src/utils/test/isStyledComponent.test.js

Unfortunately this causes rehydration breakage in dev for NextJS for some reason. Will look into it again for v5 but for now it needs to be removed.

Revert HOC detection PR

---

CHANGELOG.md
packages/styled-components/src/models/StyledComponent.js
packages/styled-components/src/models/StyledNativeComponent.js
packages/styled-components/src/test/basic.test.js
packages/styled-components/src/utils/isStyledComponent.js

originally introduced in 4.x this apparently breaks rehydration / HMR
in development runtimes pretty badly; needs potentially a different
implementation and more testing

revert self-reference check to avoid folding over HOCs

---

packages/styled-components/src/models/ServerStyleSheet.js
packages/styled-components/src/models/test/StyleSheetManager.test.js

add an alias "instance" to `ServerStyleSheet` so doing things the v4 way will continue to work
fixes #2637

ssr backward-compat fix for ServerStyleSheet

---

packages/styled-components/package.json
packages/styled-components/src/models/StyleSheetManager.js
packages/styled-components/src/models/test/StyleSheetManager.test.js
packages/styled-components/src/utils/stylis.js
yarn.lock

Drops the bundle size by a fair amount (12.1kB vs 13.62kB)... the downside is you
[can't customize stylis options anymore](https://www.npmjs.com/package/@emotion/stylis) but still can supply plugins.
I think it's an acceptable compromise for the bundle size win?

[rfc] use @emotion/stylis

---

packages/styled-components/src/test/warnTooManyClasses.test.js
packages/styled-components/src/utils/createWarnTooManyClasses.js

If your component is dynamic enough to have 20+ styling permutations
it's probably time to inline some stuff or the stylesheet will
be massive.

lower the threshold for the "too many classes" warning

---

packages/styled-components/src/models/StyledComponent.js
packages/styled-components/src/test/__snapshots__/attrs.test.js.snap
packages/styled-components/src/test/__snapshots__/expanded-api.test.js.snap
packages/styled-components/src/test/expanded-api.test.js

since we literally concat the styles together and make an entirely
new component, we don't have to care about what the layers were
that came before and in v5 it actually causes issues to keep that
information around because the base layer could be mounted later
than the overridden component and cause specificity issues

remove the concept of foldedComponentIds

---

packages/styled-components/src/models/ComponentStyle.js
packages/styled-components/src/models/StyledComponent.js
packages/styled-components/src/test/__snapshots__/attrs.test.js.snap
packages/styled-components/src/test/__snapshots__/expanded-api.test.js.snap
packages/styled-components/src/test/__snapshots__/ssr.test.js.snap
packages/styled-components/src/test/constants.test.js
packages/styled-components/src/test/expanded-api.test.js
packages/styled-components/src/test/ssr.test.js
packages/styled-components/src/test/styles.test.js

This PR reverts the change to remove `foldedComponentIds` and reintroduces some v4 behavior to not inject styles into the static component classes.
Without these changes components targeted via component selector that have been wrapped in any way (css prop, styled() hoc, etc.) will not be found for style application which is a regression from v4.
In order to reintroduce `foldedComponentIds` we need to go back to the previous behavior in v4 of not injecting styles into the component stable ssr className so that it remains available for placeholder / targeting usage only.

fix component selectors + css prop usage

---

packages/styled-components/src/models/ThemeProvider.js

We can get rid of that restriction because ThemeProvider uses stable React Context API and children cannot be a top-level element.
Fixes #1325.
The documentation will be updated too.

Get rid of the ThemeProvider single child context restriction

---

packages/styled-components/src/models/ThemeProvider.js

This is the follow-up to https://github.com/styled-components/styled-components/pull/2706.

Get rid of the ThemeProvider single child context restriction (canary)

---

CHANGELOG.md
packages/styled-components/src/models/ComponentStyle.js
packages/styled-components/src/test/staticCaching.test.js

backport dev SSR classname mismatch fix from canary

---

packages/styled-components/src/base.js

Going to add a section to FAQ about deduping the library within
environments like jest. Not sure why this was so tightly restricted
before because it's a totally valid warning even for browser-like
SSR use cases.

show the multi instance warning for all envs

---

CHANGELOG.md
packages/styled-components/src/sheet/Rehydration.js
packages/styled-components/src/sheet/Tag.js
packages/styled-components/src/sheet/dom.js

Same PR as #2721 against canary.
(Replaced the global document variables with ownerDocument so that the code works correctly on Edge.)

Use ownerDocument instead of global document (canary)

---

packages/styled-components/src/utils/createWarnTooManyClasses.js

The following warning is triggered when there are too many style updates on a component:
```
Over 200 classes were generated for component ModifiedComponent. 
Consider using the attrs method, together with a style object for frequently changed styles.
Example:
const Component = styled.div.attrs({
style: ({ background }) => ({
background,
}),
})`width: 100%;`
<Component />
```
Unfortunately, updating the implementation of `ModifiedComponent` to match the suggestion brings up a new warning about the deprecated use of `attrs`:
```
Functions as object-form attrs({}) keys are now deprecated and will be removed in a future version of styled-components. Switch to the new attrs(props => ({})) syntax instead for easier and more powerful composition. The attrs key in question is "style" on …
```

Remove deprecated attrs suggestion from too many classes warning

---

CHANGELOG.md
packages/styled-components/src/models/StyleTags.js
packages/styled-components/src/utils/insertRuleHelpers.js

It seems that on Microsoft Edge, you cannot appendChild an Element from different Document.
This causes a problem, for example, when you are using StyleSheetManager with a new window created by window.open, like this code:
```jsx
import React from 'react';
import { createPortal } from 'react-dom';
import styled, {StyleSheetManager} from 'styled-components';
export const NewWindow = props => {
const [newWindowBody, setNewWindowBody] = React.useState(null);
const unloaded = React.useRef(false);
React.useEffect(() => {
if (!unloaded.current && !newWindowBody) {
const w = window.open("about:blank");
w.addEventListener('load', () => {
setNewWindowBody(w.document.body);
});
w.addEventListener('unload', () => {
unloaded.current = true;
setNewWindowBody(null);
}); …
```

Use ownerDocument instead of global document

---

CHANGELOG.md
packages/styled-components/src/constructors/test/createGlobalStyle.test.js
packages/styled-components/src/models/StyleTags.js

Hi, thanks for the great work and amazing lib.
We have a special use case of React and styled-components:
- Rendering React App inside shadow DOM
- Unmount React App when web component tag removed from DOM (in disconnectedCallback function)
When un-mounting the app, what I found is the sheet property in \<style\> tag made by makeSpeedyTag() function is null, because when disconnectedCallback getting called, the style DOM node is already removed from DOM.
Because sheet is empty, currently styled-components throws an exception in [sheetForTag](https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/utils/insertRuleHelpers.js#L23) function.
By checking the [isConnected](https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected) flag, we know …

fix: add check for style tag detached and then removed - sheet in the style tag is null in this case

---

CHANGELOG.md
packages/styled-components/src/sheet/Rehydration.js
packages/styled-components/src/sheet/Tag.js
packages/styled-components/src/sheet/dom.js

This reverts commit 51bf23de7d6c0832189147d492aa8574d5692011.
This appears to break SSR rehydration for some reason.

Revert "Use ownerDocument instead of global document (#2726)"

---

packages/styled-components/src/models/ThemeProvider.js
packages/styled-components/src/utils/errors.md

Super small change, just for the sake of keeping errors dead simple and straightforward.
I think that theres a chance that it might save someone a bit of confusion.

Make ThemeProvider error straightforward

---

CHANGELOG.md
packages/styled-components/src/native/index.js

Hello 👋🏾,
This bug surfaced as a result of trying to use styled-components in an Expo universal project (React Native + React Native Web). `react-native-web` doesn't use default exports like `react-native` official does, so importing using ES6 default imports breaks it for that react native renderer (`TypeError: Cannot read property 'View' of undefined`). Using `require` creates the desired behavior both in `react-native` and `react-native-web` without tripping up the `navigator is deprecated and has been removed from this package.` invariant that pops up when trying to use `import  * as reactNative from 'react-native'`.
It's a pretty simple fix and all of the tests passed, so I hope that this is easy to review and possibly merge.
Thanks!
fixes #2624
-- Juwan Wheatley (@fiberjw)

[bugfix] fix imports for react-native-web

---

packages/styled-components/src/models/ThemeProvider.js

Should fix #2767
Even if `props.theme` is a function, the result should be deterministic based on `outerTheme`.

Memoize theme

---

packages/styled-components/src/constructors/createGlobalStyle.js
packages/styled-components/src/constructors/test/createGlobalStyle.test.js
packages/styled-components/src/models/GlobalStyle.js
packages/styled-components/src/test/__snapshots__/ssr.test.js.snap
packages/styled-components/src/test/rehydration.test.js

fixes #2769 #2739
cGS has a different injection profile than typical components, in that
there is a single component ID for the global style and any number of
instances. This creates problems when rendering multiple of the same
cGS with different props, as it is a defacto singleton but we don't
enforce a single cGS instance at once...
Utilizing a simple sharding strategy will create duplicate styles, but
ensure that when instances are removed from the page they're taken out
of the stylesheet in the proper order such that previous still-live
instances will continue to function and not be removed as well.
Not working: https://codesandbox.io/embed/style-with-styled-components-kvsrk
Working: https://codesandbox.io/s/style-with-styled-components-bs4mw

shard cGS by runtime instance

---

CHANGELOG.md
packages/styled-components/package.json
yarn.lock

- Will now console.warn when omitting units on properties that require them (top, width etc.)
- Fixed issue with percentage flex basis in flex shorthand
- Removed support for unitless line height in font shorthand
This should close #2782

Update css-to-react-native to v3.0.0

---

CHANGELOG.md
packages/styled-components/src/models/StyledComponent.js
packages/styled-components/src/test/attrs.test.js
packages/styled-components/src/utils/joinStrings.js
packages/styled-components/src/utils/test/joinStrings.test.js

fixes #2839
Normally attrs fully override the previous value, but in the case of
className they're often composed additively and it's desired to retain
the previous value in a HOC or folding scenario.

(v5) aggregate classNames passed via attrs 

---

.github/workflows/main.yml

Closes #2836
Comment should look exactly as https://github.com/styled-components/styled-components/pull/1652#issuecomment-380669357
I'll need you @mxstbr to add a scope of `public_repo` to the token so that it has rights to comment.
After the merge, as I'm not in the collaborators team I should be added there and get a comment. On the next PR's I should no longer receive a comment.

Update `inclusive organization` action to add contributors to a team and add a comment

---

packages/styled-components/src/sheet/Rehydration.js

replace rehydration from CSSOM with progressive regex

---

packages/styled-components/src/constructors/css.js

Based on previous question on twitter: https://twitter.com/elvepor/status/1200172654340259840
I believe that some performance of `css` construct could be saved when it doesn't have any interpolations. IMHO we can return just the styles that doesn't have to be flattened and interleaved.
Flow suppress comment is not necessary, but then I have to declare new array and return it: `[styles[0]]`.
I didn't add any new tests as this case is already covered.

Unnecessary flattening and interleave of css without interpolations

---

packages/styled-components/package.json
packages/styled-components/scripts/postinstall.js

Thank you for the amazing library!!!
npm supports the`funding` field at v6.13 and Node has updated the bundled npm version to v6.13.4 because of the vulnerability so I think many people are able to use the `fund` subcommand.
- https://github.com/npm/cli/releases/tag/v6.13.0
- https://nodejs.org/en/blog/vulnerability/december-2019-security-releases/
So could you consider to use the `funding` field instead of `postinstall`? 🙏 
I understand that printing a message while installing the package is effective to reach out to many developers but the script is very dangerous so it would be nice if the ecosystem could avoid using this.
Yarn is considering to disable the script by default.
https://github.com/yarnpkg/yarn/issues/7761#issuecomment-565493023

use funding field instead of postinstall script

---

packages/styled-components/src/base.js

Inspired by React's API: https://github.com/facebook/react/blob/master/packages/react/src/React.js#L105
My company has multiple teams working with styled-components on a shared eco-system. Although there are warnings for multiple style-component versions in the development build, our collisions often occur in the e2e environment where we use the production bundle of styled-components. This, of course, is a specific use case but I'm sure there are similar situations amongst different organizations and exposing the bundle version seems very low-cost to me.

Expose version in API

---

packages/styled-components/src/constructors/createGlobalStyle.js
packages/styled-components/src/sheet/Sheet.js
packages/styled-components/src/sheet/types.js
packages/styled-components/src/test/rehydration.test.js

fixes #2913
Previously the cGS instance count was managed locally in the cGS factory,
which works fine client-side but will never be reset properly for
server-side rendering (in this case, each cGS factory should be reset
to an instance count of 0 per rendering run.)

allocate cGS instances from the stylesheet instead

---

CHANGELOG.md
packages/styled-components/src/native/index.js

Hi folks, just noticed that useTheme wasn't exported for native so I've added it. First PR to styled-components so apologies if I've missed a contributing rule!

Add useTheme to the list of native exports

---

packages/styled-components/src/models/ServerStyleSheet.js
packages/styled-components/src/test/__snapshots__/ssr.test.js.snap
packages/styled-components/src/test/ssr.test.js

by mirroring attribute key in value. This fixes xhtml support as xml doesn't support attribute minimization (excluding the attribute value).
More specifically from [xhtml spec](https://www.w3.org/TR/xhtml1/) 4.5. Attribute Minimization
"XML does not support attribute minimization. Attribute-value pairs must be written in full. Attribute names such as compact and checked cannot occur in elements without their value being specified."
Without this, xhtml is not supported rendering the hbbtv tv platform outside the scope of styled-components. This worked in v4 as we are currently running it and are very pleased so thanks for all the good work!
ssr of any page with xhtml doctype
[Borked v5 with xhtml doctype on codesandbox.io](https://codesandbox.io/s/flamboyant-golick-8fbqe)
styled-components …

Fix xhtml compat for ssr stylesheet (works in v4)

---

CHANGELOG.md
packages/styled-components/src/sheet/GroupIDAllocator.js
packages/styled-components/src/sheet/GroupedTag.js
packages/styled-components/src/sheet/dom.js
packages/styled-components/src/sheet/test/GroupIDAllocator.test.js
packages/styled-components/src/sheet/test/GroupedTag.test.js
packages/styled-components/src/utils/errors.md

Fix #2994 
Fix #2979
Previously the formula for increasing the size of Uint32Arrays
in the GroupedTag was a little aggressive and would cut of very
short of 2^31 groups. Instead it would cut off between 2^12 and
2^13 components, which isn't quite a lot.
This new upper boundary is the absolute limit of how many slots
a Uint32Array is defined to be able to hold. After this limit we'll
see an error.
Instead of letting this error leak out we now throw a more clear
error that hints at this limitation.
I've also refactored `dom.js` to finally use `throwStyledError` as well.
Tests have been updated to reflect all changes.

Fix upper group limit in GroupedTag

---

CHANGELOG.md
packages/styled-components/src/constants.js
packages/styled-components/src/sheet/GroupedTag.js
packages/styled-components/src/sheet/Rehydration.js
packages/styled-components/src/sheet/test/GroupedTag.test.js
packages/styled-components/src/sheet/test/Rehydration.test.js
packages/styled-components/src/test/__snapshots__/ssr.test.js.snap
packages/styled-components/src/test/rehydration.test.js
packages/styled-components/src/test/ssr.test.js

revise SSR+hydration functionality to be more fault-tolerant

---

packages/styled-components/src/models/StyledComponent.js
packages/styled-components/src/test/__snapshots__/props.test.js.snap
packages/styled-components/src/test/props.test.js

Following discussion elsewhere, such as on #2780, re-opening this PR (previously #2392)
adds support for use of `shouldForwardProp` config method, which can be used to explicitly determine which props should be forwarded on
if this config is not provided then existing functionality is preserved (i.e. all props passed to components, or for HTML elements check using `validAttr`)
Inspired by the same feature in emotion
Resolve #439 
Resolve #2878

shouldForwardProp support

---

packages/styled-components/src/models/StyledComponent.js
packages/styled-components/src/models/StyledNativeComponent.js
packages/styled-components/src/native/test/__snapshots__/native.test.js.snap
packages/styled-components/src/native/test/native.test.js
packages/styled-components/src/test/props.test.js

As an alternate (but complementary) pattern to `shouldFilterProp`, this implements the proposal detailed here: https://medium.com/@probablyup/introducing-transient-props-f35fd5203e0c

transient props

---

packages/styled-components/src/utils/isPlainObject.js
packages/styled-components/src/utils/test/isPlainObject.test.js

Change isPlainObject to support objects created in a different context

---

CHANGELOG.md
packages/styled-components/src/utils/escape.js

The list of characters to be escaped was determined by the [_serialize an identifier_](https://www.w3.org/TR/cssom-1/#serialize-an-identifier) idiom of the CSSOM spec:
>- _[Ignored rules about control characters and non-letter first symbols…]_
>- If the character is not handled by one of the above rules and is greater than or equal to U+0080, is "-" (U+002D) or "_" (U+005F), or is in one of the ranges [0-9] (U+0030 to U+0039), [A-Z] (U+0041 to U+005A), or \[a-z] (U+0061 to U+007A), then the character itself.
>- Otherwise, the escaped character. 
The new list of characters in `escapeRegex` was generated by applying the rules above:
```js
const arr = [];
for (let i = 0x20; i < 0x80; ++i) {
if (
i !== 0x7f &&
i !== 0x2d &&
!(i >= 0x30 && i <= 0x39) &&
!(i >= 0x41 && i <= 0x5a) &&
i !== 0x5f …
```

fix: escape every CSS ident character necessary

---

CHANGELOG.md
packages/styled-components/src/models/StyledNativeComponent.js
packages/styled-components/src/native/test/native.test.js

Tested with `react-figma` (with `styled-components/primitives`). Should work with React Native, but would be great if someone could test it before merging 🙂.
I had to do `npm i -D bundlesize jest` in the package folder. Should I commit the `package.json` with them as local dependencies? I try to avoid global dependencies where possible (to avoid version mismatches between packages, and make sure people have up-to-date versions).
fixes #3093

Implement shouldForwardProp for React Native/Primitives

---

packages/styled-components/src/native/index.js

Add Pressable support, a new component released in React Native 0.63

Add Pressable support

---

packages/styled-components/src/utils/stylis.js

stylis.js has upgrade to v4 on 23 Apr and it's a breaking change. We should also update the url of stylis plugin accordingly, otherwise it's confusing because the current link has no info about stylis plugin.

Update stylis plugin docs url

---

CHANGELOG.md
packages/styled-components/src/models/StyleSheetManager.js
packages/styled-components/src/models/test/StyleSheetManager.test.js
packages/styled-components/src/sheet/Sheet.js

Fixes https://github.com/styled-components/styled-components/issues/2973
When looking at the thread for the above issue, I noticed that after undoing the changes from https://github.com/styled-components/styled-components/pull/2937, the issue was fixed.
It seems obvious that the `names` map change was made for a reason and I didn't want to break SSR so I settled with that solution which looks "fine" 😅
But maybe there's a better approach, if so I'd be happy to oblige 🙇‍♂️ 
I also updated the test for StyleSheetManager in order to mount `Title` both in the parent document _and_ in the iframes, as to trigger the bug in a test environment.

Pass empty `names` option to Sheet when using StyleSheetManager with custom target

---

packages/styled-components/src/models/ComponentStyle.js
packages/styled-components/src/test/staticCaching.test.js

Fixes issue raised as part of 5.2 feedback:
https://github.com/styled-components/styled-components/issues/3244#issuecomment-685625752
Please let me know if this needs any changes!

fix static styles wrapping dynamic styles being wrongly identified as static

---

packages/styled-components/src/utils/hyphenateStyleName.js

This works by:
1. avoiding work if not needed
2. lower casing individual upper case characters instead of entire strings
I discovered this could be faster when playing around in a repl and measuring the time taken to hyphenate a roughly 66% mix of camelCase names and 33% all lowercase (backgroundColor vs color etc.) (percentage taken from a large-ish project that uses styled-components).
[Unscientific perf test](https://ramdajs.com/repl/#?const%20cap%20%3D%20%2F%28%5BA-Z%5D%29%2Fg%3B%0A%0Aconst%20strs%20%3D%20%5B%0A%20%20%22helloThere%22%2C%0A%20%20%22hello%22%2C%0A%20%20%22fooBar%22%2C%0A%20%20%22test%22%2C%0A%20%20%22woahOah%22%2C%0A%20%20%22goodday%22%2C%0A%20%20%22backgroundColor%22%2C%0A%20%20%22boo%22%2C%0A%20%20%22marginRight%22%2C%0A%5D%3B%0A%0Aconst%20loop%20%3D%201000%20%2A%2050% …

potentially speed up hyphenating style names

---

packages/sandbox/server/webpack.config.js

It's PR for the following sandbox issue.
https://github.com/styled-components/styled-components/issues/3270

Fix sandbox error displaying "__SERVER__ is not defined"

---

packages/styled-components/src/base.js

The wording for this warning reads a little awkwardly, so I have updated it to flow a bit better 🙂

fix: wording in `src/packages/styled-components/base.js` warning

---

CHANGELOG.md
packages/styled-components/src/constants.js
packages/styled-components/src/test/constants.test.js

The old initialization of `DISABLE_SPEEDY` meant that the only way it could be set to a falsey value was if `NODE_ENV` was set to `production` and no other setting was set. Setting `SC_DISABLE_SPEEDY` or the environment variables to false would be overridden by `NODE_ENV`.
The new initialization ensures that if one of these options is set to false, its value is respected.
This change should only affect the computed value of `DISABLE_SPEEDY` if one of the settings has the value `false` or `’false’`. Otherwise it should have the same truthy or falsey value as before.
This basically fixes the expected behavior of setting one of the configuration variables to `false` to set `DISABLE_SPEEDY`  to false.
Note that aims to fix the same problem fixed by PR #2951, but does so without any unexpected …

fix: Allow `DISABLE_SPEEDY` to be set to `false`

---

CHANGELOG.md
packages/styled-components/src/sheet/GroupIDAllocator.js
packages/styled-components/src/sheet/test/GroupIDAllocator.test.js

Solves #2950, #2952 
For more details of the problem, see #2952 
The left side is the `reverseRegister` of the client, and the right side is the `reverseRegister` of the server.
The class `.fCnWMK` should be located 2nd, right after `.ldJpNF`. However it is in 5th on the client.
So I modified the `nextFreeGroup` setting method - to find in `reverseRegister`, not with a value greater than the added group. Also deleted the `GroupIDAllocator`'s "throws early if the group ID is too large" test which is now less significance.

Enable new style rules can be inserted in the middle of existing sheet when rendering on client after rehydrate

---

.eslintrc.json
packages/styled-components/src/models/InlineStyle.js
packages/styled-components/src/models/StyledComponent.js
packages/styled-components/src/models/StyledNativeComponent.js
packages/styled-components/src/types.js
packages/styled-components/src/utils/generateDisplayName.js
packages/styled-components/src/utils/getComponentName.js
packages/styled-components/src/utils/isTag.js

This tries to follow the same structure as `StyledComponent.js` while making the required changes for react-native.
Differences from `StyledComponent.js`
- Use `InlineStyle` instead of `ComponentStyle`
- Remove special `className` handling
- Remove too many classes warning
Differences from class implementation:
- Removed `setNativeProps` warning. This is actually tricky to do with hooks and I didn't see much value added from this warning.
- Tests / flow pass
- Tested the a large RN app using styled components still renders as before
- Tested that styled components render nicely in React DevTools (No more context provider 🎉 )

Update StyledNativeComponent to hooks

---

packages/benchmarks/src/implementations/styled-components-v5/styled-components-v5.esm.js
packages/styled-components/src/utils/flatten.js
packages/styled-components/src/utils/test/flatten.test.js

Here's an example of how this warning works now:
https://codesandbox.io/s/iselement-warning-example-32xrd
I would like to suggest to make this an error to prevent adding styles that won't work.
#3032

Refactor isElement component selector warning to be an error

---

CHANGELOG.md
packages/styled-components/src/models/StyledComponent.js
packages/styled-components/src/test/basic.test.js

fixes #2802
React doesn't alias className -> class for custom elements, so appending
styles doesn't work properly without this change

append "class" instead of "className" for unidentified DOM elements

---

packages/styled-components/rollup.config.js

Fixes: #3297 
I checked out every commit to find what caused this, and it seems that [this commit](https://github.com/styled-components/styled-components/commit/2214485f9cf5f0e0ca6b7caffd93351b2e4130d3) and [this commit](https://github.com/styled-components/styled-components/commit/4351e2b6da2d82f1167a73fe1f4aff23ba264178) were the culprit. It seems like having `window` as either `false` or `undefined` makes `jest-dom`'s `toHaveStyle` function fail by not rendering any styles at all. I imagine this has something to do with how jest interacts with the window object.
@probablyup I don't exactly know the reason behind these commits so I hope this doesn't break things elsewhere. I tested the build locally and I can confirm that this will fix `toHaveStyle`

fix styles not being added when using toHaveStyle()

---

CHANGELOG.md
packages/styled-components/src/models/StyledNativeComponent.js
packages/styled-components/src/native/test/native.test.js

When developing for react native, components are sometimes marked with
the `testID` prop. This prop is functionally similar to the
`data-testid` attached for react web components.
Unfortunately, styled components for react native didn't pass this prop
down, making it difficult for react native test frameworks like Detox to
test.
This change fixes that so when a `testID` prop is specified for a styled
component for react-native, it is passed down to the corresponding
native component it represents.
**NOTE**: Since this only affects `react-native`, it **ONLY** makes a change to `StyledNativeComponent`
**NOTE2**: I was hoping to use this change in the next minor version (`5.3.0`) which is why I branched off `legacy-v5`. Hopefully that's alright.
For context:
* [React Native Docs on …

Ensure components for react-native pass testID

---

packages/styled-components/src/macro/test/__snapshots__/macro.test.js.snap
packages/styled-components/src/macro/test/macro.test.js

This fixes a test regression introduced in a6dc34f945b22cfb4e9e7472f5a932a1e9ed8b89
The test originally mocked `cosmiconfig` to return `{ssr: false}`, but that stopped working amongst the various changes in that commit. In the meantime, `babel-plugin-tester` provides `pluginOptions` which is easier than mocking `cosmiconfig` anyway.
Fixes #3420

fix macro test regression (#3420)

---

CHANGELOG.md
packages/styled-components/package.json
packages/styled-components/src/macro/index.js
packages/styled-components/src/macro/test/__snapshots__/macro.test.js.snap
packages/styled-components/src/macro/test/macro.test.js
yarn.lock

If `styled` should come from a wrapper instead of directly from
styled-components, this enables users of the macro to customize the
import by configuring in `packages.json`:
"babelMacros": {
"styledComponents": {
"importModuleName": "my-styled-components"
}
}
Previously similar functionality landed in
babel-plugin-styled-components so users of the plugin could use
a wrapper at that level, but it wasn't available to users of the macro.
This builds on that work by passing the customized module name through
to the plugin. Consequently we also update the dependency to ensure the
plugin supports `topLevelImportPaths`
See https://github.com/styled-components/babel-plugin-styled-components/commit/325167bb570362adfb5ff78aa84c460adeae32ac
Fixes https://github.com/gregberge/xstyled/issues/44

feat: macro can customize importModuleName

---

CHANGELOG.md
packages/styled-components/package.json
packages/styled-components/src/macro/index.js
packages/styled-components/src/macro/test/__snapshots__/macro.test.js.snap
packages/styled-components/src/macro/test/macro.test.js
yarn.lock

Cherry pick these two commits from master to legacy-v5
* 7b1c3aaf fix macro test regression (#3421)
* edbe6ffb feat: macro can customize importModuleName (#3422)

Cherry pick macro fix and feature to legacy-v5

---

packages/styled-components/package.json

Enforce greater or equal version of hoist-non-react-statics

---

packages/styled-components/src/utils/stylis.js

COMPLEX_SELECTOR_PREFIX.includes wasn't transpiled,
causing issues in Internet Explorer 11 due lack of compatibility.
The fix is just replacing it for indexOf, in the meantime, the solution is to roll back to v5.2.0
CAUSE
The transpilation done with babel is not transpiling deep enough, as other Array.prototype.includes are being correctly transpiled, this single one (maybe because of being in the middle of an if statement or something fancy like that) seems to not be transpiled.
EFFECT
IE 11 is not compatible with this property of the array object, producing an error.
TEST
Compile the project and search for ".includes" in the minified file.
FIX
Replacing ".includes" for ".indexOf" for compatibility
PREVENTION
Consider adding some bundle validation as part of the Pull Request validation, …

[fix] COMPLEX_SELECTOR_PREFIX.includes wasn't transpiled

---

packages/styled-components/src/utils/nonce.js

fix #3444 by wrapping with `typeof window !== 'undefined'`
Issues was introduced by v5.2.2
Edit: 
Patch for 15b07960718a4fcd0d15ff407a4dee271e8a0c3e
Changed target branch to legacy-v5 (I hope that's the correct one..)

Fix `ReferenceError: window is undefined` Server-Side-Rendering

---

CHANGELOG.md
packages/styled-components/src/models/StyledComponent.js
packages/styled-components/src/models/StyledNativeComponent.js
packages/styled-components/src/test/props.test.js
packages/styled-components/src/types.js

Currently it's not possible to replicate styled-components' internal logic in `shouldForwardProp`, because it doesn't have all the information. It only gets the prop `key`, not `elementToBeCreated`, and so it can't properly decide in a generic manner whether to forward props.
This PR upgrades `shouldForwardProp` to include `elementToBeCreated` as a third parameter. This should be backward-compatible with existing code because it only passed two parameters previously.
This is especially for when a styled component is called with `as`, because that makes the decision of whether to forward props more dynamic than is currently possible to express.
This PR should probably also update some documentation somewhere. I can make an additional commit if it otherwise looks good to y'all.

feat: pass elementToBeCreated to shouldForwardProp

---

CHANGELOG.md
packages/styled-components/package.json
packages/styled-components/src/models/StyledNativeComponent.js
packages/styled-components/src/native/test/native.test.js
yarn.lock

This PR for v5 branch of style prop bug  fix already v5 Pressable released. More detail https://github.com/styled-components/styled-components/pull/3388.
Review in the way it says. Only difference is to checkout fix/3384_style_function_prop_for_v5 in submodule.

Fix style prop accepts function in native components for v5

---

packages/styled-components/src/constructors/css.ts
packages/styled-components/src/constructors/test/keyframes.test.tsx
packages/styled-components/src/utils/flatten.ts

See #3469 for v5.
Reimplementation of #3080. Tests pass, and I was able to recreate the intended behavior in the sandbox app.
Adds support for the following syntax:
```js
const animation = keyframes({
from: { opacity: 0 },
to: { opacity: 1 }
})
const Animated = styled.div({ animation: css`${animation} 3s` })
const Animated2 = styled.div(({time = 1}) => ({
animation: css`${animation} ${time}s infinite` 
}))
```
This addresses issue:
#2561
Note on implementation: adding the `isCss` property isn't entirely necessary. Doing a check for whether the value is an Array is sufficient. But it does seem worthwhile to refine that condition with this `isCss` check to account for other array values (perhaps someday down the road supporting fallback values with the object syntax)

Support use of css tagged template inside style objects (v6)

---

packages/styled-components/src/constructors/css.js
packages/styled-components/src/constructors/test/keyframes.test.js
packages/styled-components/src/utils/flatten.js

Reimplementation of #3080. Tests pass, and I was able to recreate the intended behavior in the sandbox app.
Adds support for the following syntax:
```js
const animation = keyframes({
from: { opacity: 0 },
to: { opacity: 1 }
})
const Animated = styled.div({ animation: css`${animation} 3s` })
const Animated2 = styled.div(({time = 1}) => ({
animation: css`${animation} ${time}s infinite` 
}))
```
This addresses issue:
#2561
Note on implementation: adding the `isCss` property isn't entirely necessary. Doing a check for whether the value is an Array is sufficient. But it does seem worthwhile to refine that condition with this `isCss` check to account for other array values (perhaps someday down the road supporting fallback values with the object syntax)

Support use of css tagged template inside style objects

---

packages/styled-components/src/models/ServerStyleSheet.js
packages/styled-components/src/sheet/Rehydration.js
packages/styled-components/src/test/ssr.test.js

Resolve #3291
_Note:_ There's no need to port this to `main` i.e. v6, as we won't be supporting IE11 for it as discussed a while ago
(For anyone following along, check #3333)

Prevent ServerStyleSheet from emitting empty tags 

---

packages/styled-components/src/base.js

Fix missing typeof window check in src/base.js (v5)

---

packages/styled-components/src/utils/checkDynamicCreation.js

This applies the same fix from #3521 to the `legacy-v5` branch.
References #3521
References #3394
References #3409

Suppress invalid hook call warning for react 18

---

packages/styled-components/src/models/ComponentStyle.js
packages/styled-components/src/sheet/GroupIDAllocator.js

Resolve #3561
Resolve #3482
Resolve #3411
Resolve #3321
Resolve #3094
Resolve #3522
Server-side rendering collisions were increasingly common in seemingly random cases, which was caused by a previous change that allowed new groups to have lower specificity and group IDs than all rehydrated groups. (See #3233)
Additionally, the hash was applied incorrectly (compare to `main` branch), where static styles would use `cssStatic.length` rather than `cssStatic`. This was previously broken due to changes in the hashing function. Overall however, this was causing issues when component IDs collided in hashes already, since `cssStatic.length` wouldn't do anything to alter the hash provided. We could still use `cssStatic.length.toString(16)` or an equivalent input, however, I've made this change to …

Fix SSR collisions caused by static style collisions and group ID minimums

---

packages/styled-components/src/constructors/createGlobalStyle.ts
packages/styled-components/src/sheet/Sheet.ts

Resolve #3506
Resolve #3369
`createGlobalStyle` components skip the synchronous insertion of styles
in the browser, which is based on a global variable. However, sheets can
be forced into server-side mode, which means we need to instead adhere
to the client-side sheet's settings.

Fix forced server-side mode not triggering global styles

---

CHANGELOG.md
packages/styled-components/src/sheet/Rehydration.ts

Resolves https://github.com/styled-components/styled-components/issues/3567
Sorry about the lack of tests. I tried adding the following test but it passes even without this change, so it's not particularly useful. I think that `innerHTML` behaves differently in actual browsers compared with the environment where the Jest tests are run (JSDOM?)
**packages/styled-components/src/sheet/test/Rehydration.test.js**
```js
it('supports > characters in selectors when style is inside another element', () => {
document.body.innerHTML = `
<svg>
<style ${SC_ATTR} ${SC_ATTR_VERSION}="${SC_VERSION}">
.b > * {}/*!sc*/
${SC_ATTR}.g22[id="idB"]{content:"nameB,"}/*!sc*/
</style>
</svg>
`;
const sheet = new StyleSheet({ isServer: true });
rehydrateSheet(sheet);
expect(sheet.getTag().getGroup(22)).toBe('.b > * …
```

Read from textContent rather than innerHTML during rehydrate

---

packages/styled-components/package.json

This PR copy the `README.md` from root to the styled-components package before publishing
Closes #3277

fix: copy readme to styled-component package before publishing

---

CHANGELOG.md
packages/styled-components/src/models/StyledNativeComponent.ts
packages/styled-components/src/native/test/native.test.tsx
packages/styled-components/src/primitives/test/__snapshots__/primitives.test.tsx.snap
packages/styled-components/src/primitives/test/primitives.test.tsx

This is somewhat similar to https://github.com/styled-components/styled-components/pull/3602 but I took a different take.
Since `generatedStyles` already seems stable, I just allow it to be passed directly to the `propsForElement` object.
The style prop will still be unstable in the case that the caller passes in some inline stables, but I think this should cover most use cases.

Stabilize style prop for React Native

---

CHANGELOG.md
packages/styled-components/package.json
packages/styled-components/src/utils/test/validAttr.test.js
yarn.lock

`translate` attribute is html global attribute, but it is not forwarded in v5.
It is added in `is-prop-valid` 1.0.0.
https://github.com/emotion-js/emotion/blob/main/packages/is-prop-valid/CHANGELOG.md

Bump is-prop-valid to forward translate attribute

---

CONTRIBUTING.md

Fixed a few small mistakes in the CONTRIBUTING.md
I saw in the history that `yarn start` was replaced by `yarn dev`, and there was a trailing backtick behind the shell command `cd packages/styled-components`

yarn start was replaced by yarn dev, removed a trailing character

---

.github/ISSUE_TEMPLATE.md

After Github purchased Spectrum all forums are now read-only, including [SC's](https://spectrum.chat/styled-components?tab=posts). Let's remove the reference to starting threads on this closed forum :smile: 
P.S. I was looking for a forum to _discuss_ pros/cons on importing theme vs getting it from the provider, which is a non-definitive question type that is out of scope for StackOverflow (i.e. will be closed). Having a new forum for such things would be great. I suggest enabling Github Discussions (which is probably povered by Spectrum code anyway).h

Remove reference to Spectrum support channel

---

package.json

The `package.json` in the base directory contained a `dev` script which in turn was related to the `dev` script of the 'packages/styled-components'. But since there is not associated `dev` script in that part of the repository, the base command fails.
This pull request addresses that small issue.

Remove: extra dev script for styled components base directory package.json

---

packages/styled-components/src/utils/isPlainObject.ts
packages/styled-components/src/utils/mixinDeep.ts
packages/styled-components/src/utils/test/isPlainObject.test.ts
packages/styled-components/src/utils/test/mixinDeep.test.ts

Fixes #3576
Since #2838, styled-components has been using a different (smaller) implementation of deep merge that doesn't play well with cyclical objects & particularly objects with cyclical prototypes.  In particular, this causes styled-components to blow the stack when used with some Function prototype extensions.
This PR replaces the mixinDeep implementation with a custom one that's closer to the [previously used library](https://github.com/mesqueeb/merge-anything) & is most similar in usage to [_.merge](https://lodash.com/docs/4.17.15#merge).  It keeps the tests unchanged, but adds a new one that explicitly ensures that cyclical objects don't blow the stack (try it with the old implementation if you want to see what happens in the current version).
See discussion in #3576 for further …

Replace mixinDeep with a cycle-safe implementation

---

packages/styled-components/src/utils/error.ts
packages/styled-components/src/utils/test/error.test.ts

All links on git.io will stop redirecting after April 29, 2022: https://github.blog/changelog/2022-04-25-git-io-deprecation/, replace all `git.io` usage with the original URL.
----
Alternative solution: use `https://styled-components.com/error#${code}` for the redirection.

refactor: replace `git.io` within error message

---

packages/styled-components/src/hoc/withTheme.spec.tsx
packages/styled-components/src/types.ts
packages/styled-components/src/utils/stylis.ts
packages/styled-components/src/utils/test/stylis.test.ts

When using CSSOM insertion any css that contains more than one rule will cause it to fail. This is because the `insertRule` api requires only one rule. To fix this we can have a custom stylis serializer that returns an array of rules instead of the default that concatenate them together.
For example this will break:
```js
styled.div`
color: red;
@media (min-height: 200px) {
color: blue;
}
`
```
since it will try to insert the following rule, which is actually 2 rules:
```
.a {color: red;} @media (min-height: 200px) {.a {color:blue;}}
```
This can be easily reproduced in the sandbox example. To make sure CSSOM is used change `DISABLE_SPEEDY` to false in `constants.ts` and run the sandbox example. You can see some styles are missing, for example the font.
Without speedy (ok):
With speedy …

Fix speedy rule insertion when css contains multiple rules

---

packages/styled-components/rollup.config.js

I briefly mentioned this on [twitter](https://twitter.com/henryqdineen/status/1565175665468530688) but we prefer, when possible for third party libraries to distribute unminified source to allow us to minify it ourselves. It seems to me that only the `.min.js` was meant to be minified so I removed the terser plugin from the others.

only minify standalone prod build

---

packages/styled-components/src/types.ts

Allow `${bool && styles}` instead of requiring `${bool ? styles : null}`

fix(types): allow interpolating false

---

packages/styled-components/src/types.ts

This is a bit opinionated, but I think there's no reason anybody should be passing both, and one benefit we get from types is avoiding those kinds of mistakes.

Disallow mix of $as and as

---

packages/styled-components/package.json
packages/styled-components/src/constructors/constructWithOptions.ts
packages/styled-components/src/models/StyledComponent.ts
packages/styled-components/src/models/StyledNativeComponent.ts
packages/styled-components/src/types.ts
packages/styled-components/src/utils/isStaticRules.ts
packages/styled-components/src/utils/isStyledComponent.ts
yarn.lock

Updating typescript revealed some issues, see full output at the bottom. This PR includes the fixes so that `tsc` runs clean again.
The most interesting part of this starts with the error:
```
src/types.ts:167:7 - error TS2344: Type 'ExpectedProps & PropsToBeInjectedIntoActualComponent'
does not satisfy the constraint '{}'.
```
which ends up bubbling upward to force changing various `Props = unknown` to `Props extends {}` or `Props extends {} = {}`. I think this is a good thing, and we should be avoiding defaulting to unknown where we can, since it causes more problems down the line.
---
Full output of `yarn tsc` after upgrade, before fixes:
```
src/models/StyledComponent.ts:62:5 - error TS2578: Unused '@ts-expect-error' directive.
62     // @ts-expect-error narrowing isn't working …
```

chore: update typescript

---

packages/styled-components/src/utils/hyphenateStyleName.ts
packages/styled-components/src/utils/test/hyphenateStyleName.test.ts

Fixes #3810. Along with not mangling, CSS vars are case sensitive so the caps need to be preserved.

fix: css vars mangled by hyphenateStyleName

---

packages/styled-components/src/constructors/constructWithOptions.ts
packages/styled-components/src/constructors/createGlobalStyle.ts
packages/styled-components/src/constructors/css.ts
packages/styled-components/src/constructors/keyframes.ts
packages/styled-components/src/hoc/withTheme.tsx
packages/styled-components/src/models/GlobalStyle.ts
packages/styled-components/src/models/InlineStyle.ts
packages/styled-components/src/models/StyledComponent.ts
packages/styled-components/src/models/StyledNativeComponent.ts
packages/styled-components/src/types.ts
packages/styled-components/src/utils/createWarnTooManyClasses.ts
packages/styled-components/src/utils/determineTheme.ts
packages/styled-components/src/utils/empties.ts
packages/styled-components/src/utils/error.ts
packages/styled-components/src/utils/flatten.ts
packages/styled-components/src/utils/interleave.ts
packages/styled-components/src/utils/isStaticRules.ts
packages/styled-components/src/utils/mixinDeep.ts

This fixes a bunch, but not all, of the problems reported in #3800 
The problems fixed:
- [styled components don't emit an error on missing props](https://github.com/styled-components/styled-components/issues/3800#issuecomment-1242746314)
- [`styled(Custom).attrs()` breaks typing of properties](https://github.com/styled-components/styled-components/issues/3800#issuecomment-1242760145)
The changes:
- kill `BaseExtensibleObject` (and use `Dict<any>` explicitly in places that need that kind of thing, where `type Dict<T> = {[k: string]: T}`)
- rename `ExtensibleObject` to `ExecutionProps` since it's essentially a partial `ExecutionContext`
- change lots of `<Props = unknown>` to `<Props extends object>` which allows TS to check and infer a bit more
- allow the `attrs` call to infer or …

collected fixes for v6 typescript

---

packages/styled-components/src/models/StyledComponent.ts
packages/styled-components/src/utils/joinStrings.ts

Prior to v6 this built a new object `propsForElement` with only the forwarded props. Since v6, it changed to mutating `context` in place, see 0b8605ab20a2c1886e4ceea7b8b7f559d820511e
The new approach keeps the props but sets them undefined. This makes React emit errors in dev and test. Delete them from the context instead.
Additionally check and delete any undefined values in context, for example if `.attrs()` sets some to undefined, they should be removed at this point.

fix: don't send undefined props to DOM

---

packages/styled-components/package.json
yarn.lock

This should enable `styled-components` to take advantage of the new support for container queries (`@container`).

Bump stylis to version 4.1.3

---

packages/styled-components/src/models/StyledNativeComponent.js

PR that broke down the logic: https://github.com/styled-components/styled-components/pull/3365/files
Currently, adding testID as an attribute in `attrs` does not work, because testID is always overwritten with regular prop as `undefined`.
This change adds the ability to specify testID with `.attrs()`, as was possible before version 5.2.2
```
const MyComponent = styled.View.attrs({ testID: 'something' })`` // such code does not work
```

fix: (React Native) passing testID as attrs property

---

packages/styled-components/src/base.ts
packages/styled-components/src/constructors/test/createGlobalStyle.test.tsx
packages/styled-components/src/constructors/test/keyframes.test.tsx
packages/styled-components/src/models/ServerStyleSheet.tsx
packages/styled-components/src/models/StyleSheetManager.tsx
packages/styled-components/src/models/test/StyleSheetManager.test.tsx
packages/styled-components/src/test/ssr.test.tsx
packages/styled-components/src/utils/stylis.ts

This obviates the corresponding babel feature and allows for namespacing in compiler environments that don't support babel.

feat(StyleSheetManager): add optional namespacing

---

packages/styled-components/src/utils/flatten.ts
packages/styled-components/src/utils/test/flatten.test.tsx

We are in the process of migrating our codebase to SC v6 and we have this case in many places:
```tsx
const StyledDiv = styled.div<{
$color: string;
}>`
${(p) => {
if (p.$color) return `color: ${p.$color}`
return null
}
`;
```
With v6, this results in the following runtime error:
```sh
Component is not a styled component and cannot be referred to via component selector. See https://www.styled-components.com/docs/advanced#referring-to-other-components for more details.
```
Realizing that the appropriate solve for this issue to remove the `return null` or to return something else instead, this error is confusing. Because `typeof null === 'object'`, the logic in `flatten.ts` incorrectly interprets the `null` as a nameless React component.
Since `null` is dropped in flatten anyway ([as …

fix: interpolation functions returning null should not console.error

---

packages/styled-components/src/constants.ts

there are times when process.env is not defined, 
let's prevent breaking at least...
related to https://github.com/cypress-io/cypress/issues/21434

fix: prevent crash when process.env is not defined

---

packages/styled-components/src/models/test/StyleSheetManager.test.tsx
packages/styled-components/src/utils/stylis.ts

The instructions on raising an issue said to consider making a PR with a failing test so here is one:
The issue this tests for is that when using an ampersand (&) to scope css to a parent selector and also using the new namespace feature added in the latest beta version, the resulting css has the parent selector before the namespace selector.
I took a stab at resolving this but while I was able to get the original issue solved, it breaks down with more complex use cases (as seen in the 2nd test)

Fixes issue when using an ampersand (&) to scope css to a parent selector alongside the new namespace feature

---

.github/workflows/test.yml
packages/styled-components/src/models/StyleSheetManager.tsx
packages/styled-components/src/models/StyledComponent.ts
packages/styled-components/src/models/test/StyleSheetManager.test.tsx

This allows for an easy upgrade path to v6 if transient props were not previously in use.

feat(StyleSheetManager): add ability to provide default shouldForwardProp

---

packages/styled-components/src/models/StyledComponent.ts

_Note: examples use the Node.js REPL with strict mode: `node --use_strict`._
Objects in JavaScript [inherit properties from their prototype chain](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain). For example, the "toString" property can be accessed on all objects, but it doesn't actually exist on each object, it exists on the global Object prototype:
```js
let obj = {};
obj.toString();
// '[object Object]'
Object.getOwnPropertyDescriptor(obj, 'toString');
// undefined
Object.getOwnPropertyDescriptor(Object.prototype, 'toString');
// { value: [Function: toString], writable: true, enumerable: false, configurable: true }
```
Under normal circumstances, you can assign a property to an object using the `=` operator, and any property of the same name …

Make styled components work when the Object prototype is frozen

---

packages/styled-components/src/utils/determineTheme.ts

It was broken by [this](https://github.com/styled-components/styled-components/commit/75d492c68caf0f1c2a7f705e734db3e41395f866#diff-36d077e5df21437167bd0eb44ec4445d43399d7aec2761bc11937d3d3a4a36deR9) change, which causes `determineTheme` to return a boolean as the right-hand side of `(props.theme && props.theme !== defaultProps.theme)` will now be a boolean, while with `(props.theme !== defaultProps.theme && props.theme)` it would be `props.theme`.

Fix determineTheme & add typing

---

packages/styled-components/src/models/StyledComponent.js

Backport of #3963 for the v5 branch!

[v5] Make styled components work when the Object prototype is frozen

---

packages/styled-components/src/constructors/keyframes.ts
packages/styled-components/src/models/ComponentStyle.ts
packages/styled-components/src/models/GlobalStyle.ts
packages/styled-components/src/models/InlineStyle.ts
packages/styled-components/src/models/ServerStyleSheet.tsx
packages/styled-components/src/models/StyledComponent.ts
packages/styled-components/src/test/utils.ts
packages/styled-components/src/types.ts
packages/styled-components/src/utils/domElements.ts
packages/styled-components/src/utils/flatten.ts
packages/styled-components/src/utils/hyphenateStyleName.ts
packages/styled-components/src/utils/joinStrings.ts
packages/styled-components/src/utils/test/joinStrings.test.ts

I was looking into using object literals instead of template literals for CSS with SC and wanted to compare performance beforehand and found a few easy wins. I used [stitches-bench](https://github.com/stitchesjs/stitches-bench) since the benchmark package in the styled-components repo hasn't been functional for a while.
I ran most of the stitches-bench benchmarks, comparing the latest `main` of styled-components with the changes here. Most tests were run for both object and template literals. All numbers given are the average time of a run. These were all based on [this commit](https://github.com/styled-components/styled-components/commit/9aa317eadc2b4f29f12080751b95ab6b8ae9ee0f), just before the recent optimizations that were pushed to main.
The gzip'd size of `styled-components.min.js` …

Optimization of hot paths

---

.github/ISSUE_TEMPLATE.md

clipboard argument in envinfo isn't supported anymore, we should directly use clipboardly or clipboard-cli.

chore: remove --clipboard option in envinfo

---

packages/styled-components/src/utils/addUnitIfNeeded.js
packages/styled-components/src/utils/test/addUnitIfNeeded.test.js

Currently, the `addUnitIfNeeded` function is adding `px` to CSS variables that could potentially be used unitless. i.e. `--tooltip-z-index` or `--font-weight-bold`. It should ignore adding `px` if it's used for CSS variables since we can't know what they are used for.

fix: Do not add px to unitless CSS variables

---

packages/styled-components/src/index.ts
packages/styled-components/src/test/types.tsx
packages/styled-components/src/types.ts

Fix the `css` prop typings to resolve TypeScript errors when using the prop (described in https://github.com/styled-components/styled-components/issues/3800#issuecomment-1498409379) and added type tests for a few common usages.
I also included some related improvements:
* Reworded and updated the `CSSProp` docblock
* Updated the example usage to augment `Attributes` rather than `DOMAttributes`. This makes it possible to use `css` with custom components whose props don't extend DOMAttributes, and matches [the example usage in DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/35f7bccf0d312292ea79feac97d3b3274d34158c/types/styled-components/index.d.ts#L431).
* Changed the description to be more oriented around the `css` prop rather than styled-components-related module …

Fix `css` prop typings

---

packages/styled-components/package.json

Remove the `shallowequal`、`stylis` and `tslib` from `peerDependencies` and `peerDependenciesMeta`
Firstly, PNPM will skip install the peer dependencies which mark as `optional: true`, even if they are declared in `dependencies`, so we will get the `Cannot resolve 'xxx'` error when compiling.
And I think these above peer dependencies should be dependencies, because `tslib` is similar to `@babel/runtime`, and the `stylis`, `shallowequal` are low-level dependencies, styled-components should not ask users for them, and the official documentation also does not require users to install them

fix: correct dep declaration for styled-components

---

packages/styled-components/src/test/types.tsx
packages/styled-components/src/utils/stylis.ts
packages/styled-components/src/utils/test/stylis.test.ts

When vendor prefixing is enabled, the default behavior in stylis is for them to come out as a clump. Unfortunately, this cases issues with CSSOM because some browsers reject rules containing styles with unknown selectors, e.g. Chrome might reject a -moz prefix or vice versa.

fix(stylis): ensure rules are split coming out of stylis

---

packages/styled-components/src/models/Keyframes.ts
packages/styled-components/src/models/StyledComponent.ts
packages/styled-components/src/models/test/Keyframes.test.ts
packages/styled-components/src/sheet/Sheet.ts
packages/styled-components/src/sheet/test/Sheet.test.ts
packages/styled-components/src/utils/setToString.ts

This PR is a follow-on to #3963. To summarize:
* Freezing the global Object prototype is one of the best ways to defend against Prototype Pollution attacks
* Doing this changes all properties of the Object prototype to become non-writable
* JavaScript does not allow you to use the "=" assignment operator to "shadow" any inherited, non-writable object properties -- in particular, the "toString" property
* The correct way to do this is to use the `Object.defineProperty()` syntax instead
I wasn't aware that this package uses Babel to transform ES6 class methods to object assignment.
For example, take this class:
```ts
class Foo {
constructor() {}
toString = () => 'bar';
}
```
If you have frozen your global Object prototype, that ES6 class method syntax would still work just fine.
However, …

Compatibility with frozen Object prototype, part 2

---

packages/styled-components/src/constructors/createGlobalStyle.ts
packages/styled-components/src/hoc/withTheme.tsx
packages/styled-components/src/models/StyledComponent.ts
packages/styled-components/src/models/StyledNativeComponent.ts
packages/styled-components/src/models/ThemeProvider.tsx
packages/styled-components/src/utils/errors.md
packages/styled-components/src/utils/errors.ts
yarn.lock

Right now the return type for `useTheme: DefaultTheme | undefined` cause the usage of the hook to be extremely inconvenient where it might be `undefined`, using the hook need to verify the themes existence inside every component.
```typescript
export default () => {
const theme: DefaultTheme | undefined = useTheme();
return (
<div>
{theme.foo.bar} // 👈 this gives an error because theme could be undefined.
<div>
);
}
```
My suggestion is to add a check, inside the hook, that the theme is set using a `ThemeProvider`, otherwise throw an error for using the hook without a `ThemeProvider`.

ensure useTheme hook returns theme object

---

packages/styled-components/src/models/StyleSheetManager.tsx

If `exactOptionalPropertyTypes` is enabled in `tsconfig.json`, this code should work:
```js
import { type ReactElement, type ReactNode } from 'react'
import { StyleSheetManager, type ServerStyleSheet } from 'styled-components'
export const Test = (
{ children, sheet }: {
readonly children: ReactNode
readonly sheet?: undefined | ServerStyleSheet['instance'] // defined only on server side
},
): ReactElement => {
return (
<StyleSheetManager
sheet={sheet}
>
{children}
</StyleSheetManager>
)
}
```
v5 types:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b384d9e82713dc8400a1289eeb9be7f2fc467390/types/styled-components/index.d.ts#L400-L407

fix: StyleSheetManager must accept undefined props

---

packages/styled-components/src/models/StyledComponent.ts
packages/styled-components/src/models/StyledNativeComponent.ts
packages/styled-components/src/sheet/dom.ts
packages/styled-components/src/types.ts

Fixes #4061
`Omit` type uses `Exclude`, it's much slower.
`CSS.Properties` type must be huge:
https://github.com/styled-components/styled-components/blob/bb1bd5a80bf46813a2c9b4635399ae04b007c942/packages/styled-components/src/types.ts#L225

fix: replace slow Omit type

---

packages/styled-components/src/constructors/createGlobalStyle.ts

Fixes: https://github.com/styled-components/styled-components/issues/4100
Current implementation conditionally uses React18 `useInsertionEffect`; but useInsertionEffect does not have a return type: https://react.dev/reference/react/useInsertionEffect#returns and the global styles will not be removed when the GlobalStyle component is unmounted.

Fix createGlobalStyle not removing styles on unmount

---

packages/styled-components/src/test/types.tsx
packages/styled-components/src/types.ts

This PR improves the types when a `StyleFunction` returns another `StyleFunction` or a `StyledObject` as the return value. This prevents type errors when component prop types are explicitly provided (i.e. `styled.div<Props>`)
Examples have been addd in `test/types.tsx` for three different test cases:
1. When a reusable `css` block is provided as an interpolation value
2. When a StyleFunction returns another StyleFunction
3. When a StyleFunction returns a StyledObject
This fixes https://github.com/styled-components/styled-components/issues/4099

Fix Typescript issues with StyleFunctions and StyledObjects

---

packages/styled-components/src/test/types.tsx
packages/styled-components/src/types.ts

Fixes https://github.com/styled-components/styled-components/issues/4090
The `TLength` generic from `CSS.Properties` defaults to `TLength = 0 | (string & {})`, I verified that before my change I am able to provide `0`, but any other size needs to be a string.
With this changed to `number | (string & {})` I can provide any number or string.
I also added a test for this, providing the number as a height presented a type error before this fix but is resolved after.

fix(types): allow number for height/width/etc (#4090)

---

packages/styled-components/src/index.ts
packages/styled-components/src/native/index.ts
packages/styled-components/src/types.ts

https://github.com/styled-components/styled-components/issues/4062
I found that styled-components has lost some types since v6. There is actually an issue.
I added some of them.
- CSSProperties
- CSSObject
- CSSPseudos
- CSSKeyframes
I tried to work on the other types, but they were too complicated, so I am dealing with what I can for now.

Add missing types CSSProperties, CSSObject, CSSPseudos and CSSKeyframes

---

CONTRIBUTING.md

Looks like the benchmarks were moved into their own package; this PR updates the instructions on how to run them.

Updated Contributing guide benchmark instructions

---

packages/styled-components/src/models/ComponentStyle.ts
packages/styled-components/src/test/basic.test.tsx

This PR fixes https://github.com/styled-components/styled-components/issues/4113
This problem occurs when dynamic interpolations in different places can return the same value. 
An example of how this problem can happen:
```ts
const MyComponent = styled.div<{ $variant: 'text' | 'background' }>`
color: ${props => props.$variant == 'text' && 'red'};
background-color: ${props => props.$variant == 'background' && 'red'};
`;
```
In the example above, there are two interpolation functions. Each returns the exact same value, but appears next to a different CSS property name. 
In production builds, the logic which determines if a new class name needs to be created fails to check for this situation and outputs the same CSS for both `<MyComponent $variant="text" />` and `<MyComponent …

Fix production mode inconsistent CSS rendering when dynamic property values are the same but property names are different

---

packages/styled-components/src/base.ts
packages/styled-components/src/index.ts
packages/styled-components/src/types.ts
packages/styled-components/src/utils/domElements.ts

As libraries like `@react-three/fiber` add to JSX.IntrinsicElements, it can get too large to convert to a union in some scenarios. I'm using the tag name maps from `lib.dom.d.ts` instead. In an environment with no JSX augmentations, this results in the same union.
For example, in the case of `@react-three/fiber`, the original union looks something like this:
`'h1' | 'h2' | 'h3' | 'meshPhysicalMaterial' | 'meshStandardMaterial' | 'meshPhongMaterial' ...`
And the new one only includes standard HTML tag names:
`'h1' | 'h2' | 'h3' ...`
From what I can tell, this is what makes sense. (Any edge cases this would screw up?)
fixes #4115

fix: union type too complex

---

packages/styled-components/package.json
yarn.lock

Fix security vulnerability related to `postcss` dependency [Link to the issue](https://security.snyk.io/vuln/SNYK-JS-POSTCSS-5926692)
- https://github.com/styled-components/styled-components/issues/4186

Bump postcss version from 8.4.23 to 8.4.31

---

packages/styled-components/src/types.ts

At lines 265 and 269 are same types. 
https://github.com/styled-components/styled-components/blob/main/packages/styled-components/src/types.ts#L262-L272
Therefore, there should be no problem even if one is deleted.

Remove deplicated type `StyledObject<Props>`

---

packages/styled-components/src/models/InlineStyle.ts
packages/styled-components/src/native/index.ts
packages/styled-components/src/native/test/native.test.tsx
yarn.lock

Hi,
According to the current RN [docs](https://reactnative.dev/docs/image-style-props#props), those styles `borderColor, borderWidth, borderStyle` can be only one instead of multiple.
Note: how I can test those changes?
Fixes https://github.com/styled-components/styled-components/issues/4181

fix image unsupported border color style

---

packages/styled-components/src/hoc/withTheme.tsx
packages/styled-components/src/models/StyledComponent.ts
packages/styled-components/src/models/StyledNativeComponent.ts

Description in this issue: https://github.com/styled-components/styled-components/issues/4207
This PR simply reverts the commit that has removed the display name on react components in production env.

Keep displayName in production environment

---

packages/styled-components/src/types.ts

Fixes #4229
Emitted declaration files end up very large because HTML props are explicitly listed instead of referencing the `FastOmit` type. This causes a huge performance loss due to larger `.d.ts` files needing to be written, as well as a much larger file size.
I myself noticed my builds taking 2x-3x longer due to the shear amount of additional writes to disk having to happen.
The bug happens because `FastOmit` is not exposed, so TypeScript ends up explicitly defining the resulting type instead.  Exposing `FastOmit` fixes the issue.

Expose FastOmit to improve emit performance

---

.github/workflows/codeql-analysis.yml
.github/workflows/test.yml
packages/styled-components/package.json
packages/styled-components/src/test/styles.test.tsx
yarn.lock

In some circumstances, prior versions of stylis would not properly
apply the component namespace to a nested rule when using comma-joined
selector chains, e.g. `&.foo, p:not(:last-child)`.
Fixes #4224 
Thank you very much @Andarist for patching!

fix: bump stylis to 4.3.1 to resolve issue with leaking nested selectors 

---

packages/styled-components/src/constructors/constructWithOptions.ts
packages/styled-components/src/test/types.tsx

closes #4076
closes #4138
closes #4183
Hello, the above issue is blocking us from upgrading to v6, so here is a possible fix.
The improvement brought by this PR can be seen in this example:
```tsx
const DivWithRequiredFooBar = styled.div<{ foo: number; bar: string }>``;
// foo is provided, so it becomes optional
const DivWithRequiredBar = styled(DivWithRequiredFooBar).attrs({ foo: 42 })`
margin; ${props => props.foo * 10}px;
`;
// @ts-expect-error must provide bar
<DivWithRequiredBar />;
// OK (NEW)
<DivWithRequiredBar bar="3" />;
// OK. Can still provide foo if we want
<DivWithRequiredBar foo={3} bar="3" />;
// @ts-expect-error foo must be a number
<DivWithRequiredBar foo="3" bar="3" />;
```
The part marked as `(NEW)` is made possible by this PR. Once `foo` is provided through the …

fix: improve types for .attrs()

---

packages/styled-components/src/test/types.tsx
packages/styled-components/src/types.ts

In v6 it's currently not possible to use a styled-component as a key inside object styles to reference its class name, because TypeScript is not happy about:
> A computed property name must be of type 'string', 'number', 'symbol', or 'any'.
This PR adds the same hack available in the older `@types/styled-components` package intersecting the main `IStyledComponent` type with the `string` type, available only in the web runtime.
Basically, this becomes possible:
```ts
const H1 = styled.h1({
fontSize: '2rem'
})
const Header = styled.header({
[H1]: {
marginBottom: '1rem'
}
})
```
---
I realize this can be worked around by wrapping they key in either:
1. `H1.toString()`
1. `String(H1)`
2. a template string `${H1}`
but in my opinion it's a bit annoying.
Would be willing to accept this PR? What …

fix(types): allow using a styled component as a key inside object styles in the web runtime

---

packages/styled-components/src/constructors/styled.tsx
packages/styled-components/src/index.ts

This PR exposes some new types that are intended to aid in third-party library adoption for scenarios where the library is wrapping `styled-components` and injecting additional props.
The new types are:
- `LibraryStyled`: a higher-order type that takes `LibraryProps` and merges them in with any downstream component props
- `Styled`: the type for the `styled()` HOC (the same as `typeof styled`)
- `StyledInstance`: the return type for a usage of the `styled()` HOC
The `FastOmit` type has also been exposed to make it more convenient to match behaviors.

feat(types): add types to support third-party wrapping scenarios

---

packages/styled-components/src/sheet/Sheet.ts
packages/styled-components/src/sheet/types.ts

This will help rehydrate sheet on NextJS/React 18 streaming when initial rehydration is already done and we receive a new chunk from NextJS `useServerInsertedHTML` afterwards.
With this change we can manually get the stylesheet and call rehydration.

Export rehydrate from StyleSheet

---

packages/styled-components/src/models/ServerStyleSheet.tsx
packages/styled-components/src/sheet/Rehydration.ts
packages/styled-components/src/test/__snapshots__/ssr.test.tsx.snap
packages/styled-components/src/test/ssr.test.tsx

It seems like this PR not ported over to v6 and with React 18 streaming, it's possible to insert empty style tag in middle of html.
It should fix this issue: https://github.com/styled-components/styled-components/issues/4289
Ported over from: https://github.com/styled-components/styled-components/commit/b9e60f7efb66c0710002f0e133e42af1c7deb497

Prevent ServerStyleSheet generating empty style tags/elements

---

packages/styled-components/src/constructors/styled.tsx
packages/styled-components/src/constructors/test/createGlobalStyle.ssr.test.tsx
packages/styled-components/src/constructors/test/createGlobalStyle.test.tsx
packages/styled-components/src/hoc/withTheme.tsx
packages/styled-components/src/models/ServerStyleSheet.tsx
packages/styled-components/src/models/StyleSheetManager.tsx
packages/styled-components/src/models/ThemeProvider.tsx
packages/styled-components/src/test/props.test.tsx
packages/styled-components/src/test/ssr.test.tsx
packages/styled-components/src/test/types.tsx
packages/styled-components/src/types.ts

The global `JSX` namespace is [deprecated](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#the-jsx-namespace-in-typescript). This Replaces it with `React.JSX`.
Motivation:
This will make the library compatible with `types-react@19.0.0-rc.1` (Upcoming `@types/react` version). It comes at no backwards compatibility cost, the `React.JSX` namespace is already used in some places. At MUI we need `@types/react@19` compatibility (but not necessarily `react@19` compatibility) for https://github.com/mui/material-ui/pull/42824.

Replace deprecated global JSX namespace

---

packages/styled-components/src/models/StyleSheetManager.tsx
packages/styled-components/src/sheet/Sheet.ts
packages/styled-components/src/sheet/Tag.ts
packages/styled-components/src/sheet/dom.ts
packages/styled-components/src/sheet/types.ts
packages/styled-components/src/types.ts

In `@types/styled-components`, the `target` prop of `StyleSheetManager` allows passing a `ShadowRoot` (see [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/86953d1148f231c8f1c534e4a718ac4fa7888767/types/styled-components/index.d.ts#L390-L397)).
As I'm not familiar with this codebase, I started from the change to `IStyleSheetManager`, then fixed any type errors that surfaced. @quantizor please let me know if you see any problems with what I've done here, or if you know of a reason why the `ShadowRoot` option wasn't carried over into v6!

Allow Passing Shadow Root as Sheet Target

---

.changeset/tough-eyes-thank.md
packages/styled-components/src/models/StyledComponent.ts
packages/styled-components/src/models/StyledNativeComponent.ts

Prevent styled() from injecting an undefined ref prop in React 19

---

.changeset/two-rockets-pay.md
packages/styled-components/package.json
yarn.lock

chore: update postcss to version 8.4.49 and nanoid to version 3.3.8

---

.changeset/nasty-kids-count.md
packages/styled-components/rollup.config.mjs

This should address #5516 (and probably some similar issues). The gist of it is that when the library is built, native/dist should have the typings alongside of the cjs and esm builds, but it doesn't by default (I do see the files in the published package, but they're under native/dist/dist instead of native/dist, I guess something manual was done before publishing the package like a cp command that missed/had one too many leading slashes in it?). So this change updates the typescript's outDir for the native compilation to properly output into the native/dist folder.

fix: release of native typings wasn't working

---

.changeset/small-cows-dance.md
packages/styled-components/src/utils/checkDynamicCreation.ts

Hi,
I added a documentation link for the Dynamic Creation console warning.
(It took me a while to understand why it must be defined outside the render method.)
I also added a line break at the end because 'Error Component Stack' was continuing without a line break.

fix: add documentation link for Dynamic Creation console warning

---

.changeset/afraid-plants-bathe.md
packages/styled-components/src/hoc/withTheme.tsx
packages/styled-components/src/utils/hoist.ts

the `withTheme` types in the build output still referenced the old `JSX` namespace instead of `React.JSX`
this caused issues in react 19 where the old `JSX` namespace was removed.
fixes https://github.com/styled-components/styled-components/issues/4359

fix: react 19 compatibility
